create_symlinks() v1.0
fixup

diff --git a/bore b/bore
--- a/bore
+++ b/bore
@@ -89,12 +89,37 @@ addpkg() {
     # run build() method inside pkgfile
     if build ; then
         rm -r "$work"/"${pkg}${delim}${version}"
+        create_symlinks $pkg
         echo "${pkg}${delim}${version}" >> "$boredb"
         echo "$pkg installed!"
         clean
     else
         die "$pkg build() failed"
     fi
+}
+
+# creates symlinks for a port
+create_symlinks() {
+    pkg=$1
+    # sym link all $opt/$pkg/$dir to the /$dir
+    for dir in bin sbin etc share include lib ; do
+        for subdir in $(find "$opt/$pkg/$dir" ! -path "*$dir" \
+                ! -path "*$pkg/share/man" -maxdepth 1 2> /dev/null) ; do
+            [ -e "$subdir" ] || continue
+            subdir="$(basename $subdir)"
+            ln -s "$opt/$pkg/$dir/$subdir" "/$dir/$subdir" || 
+                die "failed to link $dir for $pkg"
+        done
+    done
+    # man pages
+    $mans &&
+        for page in $(find "$opt/$pkg/share/man/man1" \
+                ! -path "*/man1" 2> /dev/null) ; do
+            [ -e "$page" ] || continue
+            i=$(basename $page)
+            ln -s "$opt/$pkg/share/man/man1/$page" "/share/man/man1/$page" || 
+                    die "Failed to link man pages for $pkg"
+        done
 }
 
 # downloads to $sources and extracts to $work
@@ -266,8 +291,8 @@ main() {
             isinst|-i) isinst $2 ; exit $? ;;
             list|-l)   cat "$boredb" ; exit $? ;;
             count|-c)  cat "$db" | wc -l | sed 's/ //' ; exit ;;
-            *help|-h)  usage ;;
             --opt=*|--src=*) shift ;; # see above
+            *help|-h)  usage ;;
             *) if [ -n "$1" ] ; then
                    addpkg $1
                    exit $?
