add --opt=|--src= chroot bootstrap system

diff --git a/bore b/bore
--- a/bore
+++ b/bore
@@ -23,21 +23,17 @@ EOF
 exit
 }
 
-borerc=/src/bore.rc
-. $borerc || die "Error: Could not source $borerc"
-
 clean() {
-    if [ -z "$work" ] || [ -z "$opt" ] || [ "$opt" = / ] ; then
-        die "Error: $work or $opt were unset!"
-    fi
+    # sanity check
+    for var in bore opt src work boredb ; do
+        [ -n "$var" ] || exit 1
+    done
 
-    [ -n "$work" ] &&
-        rm -rf "$work"/*
+    rm -rf "$work"/*
 
     # remove empty dirs in $opt
     for dir in $(find "$opt" -nowarn -type d ! -wholename "$opt") ; do
-        [ -z "$(ls $dir)" ] &&
-            rm -r "$dir"
+        rmdir "$dir" 2> /dev/null
     done
 
     if [ -f "$boredb" ] ; then
@@ -232,22 +228,43 @@ isinst() {
 }
 
 main() {
-    clean
-    case "$1" in
-        add|-a)    addpkg $2 ; exit $? ;;
-        del|-d)    delpkg $2 ; exit $? ;;
-        search|-s) search $2 ; exit $? ;;
-        isinst|-i) isinst $2 ; exit $? ;;
-        list|-l)   cat "$boredb"       ;;
-        count|-c)  cat "$db" | wc -l | sed 's/ //' ;;
-        *help|-h)  usage ;;
-        *) if [ -n "$1" ] ; then
-            addpkg $1
-            exit $?
-        else
-            usage
-        fi
-    esac
+    
+    # Warning: These options are used when bootstrapping a system.
+    #          ... calling them otherwise is not recommended.
+    for arg in "$@" ; do
+        case "$arg" in
+            --src=*) chroot_src="${arg#--src=}" ;;
+            --opt=*) chroot_opt="${arg#--opt=}"
+        esac
+    done
+
+    if [ -z "$chroot_src" ] ; then
+        . /src/bore.rc || die "Error: Could not source /src/bore.rc"
+    else
+        . "$chroot_src"/bore.rc || 
+            die "Error: Could not source $chroot_src/bore.rc"
+        opt="$chroot_opt"
+        src="$chroot_src"
+    fi
+
+    while [ $# -gt 0 ] ; do
+        case "$1" in
+            add|-a)    addpkg $2 ; exit $? ;;
+            del|-d)    delpkg $2 ; exit $? ;;
+            search|-s) search $2 ; exit $? ;;
+            isinst|-i) isinst $2 ; exit $? ;;
+            list|-l)   cat "$boredb"     ; exit $? ;;
+            count|-c)  cat "$db" | wc -l | sed 's/ //' ; exit $? ;;
+            *help|-h)  usage ;;
+            --opt=*|--src=*) shift ;; # see above
+            *) if [ -n "$1" ] ; then
+                    addpkg $1
+                    exit $?
+                else
+                    usage
+                fi
+        esac
+    done
 }
 
 main "$@"
