updates

diff --git a/src/add b/src/add
--- a/src/add
+++ b/src/add
@@ -3,12 +3,49 @@
 # -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 
 add() {
-    for p ; do
-        # check if pkg is already installed (-f to force)
-        case $1 in
-            -f) isinst "$p" && warn "$p is already installed" ; shift ;;
-            *) isinst "$p" && die  "$p is already installed"
+    # packages we have been asked to add
+    mainpkgs=$*
+
+    # clear the array, we will use it to build the list
+    set --
+
+    for p in $mainpkgs ; do
+        # grab initial package variables
+        loadpkgfile "$p"
+
+        # search for dependencies, the value is stored in $pkgdeps
+        pkgdeps "$p"
+
+        # add deps to list, before the main package
+        case $pkgdeps in
+            ""|"* *") ;; # if unset or empty string, there are no deps
+            *)
+                for dep in $pkgdeps ; do
+                    # if dep is not installed, schedule it to be added
+                    if ! isinst "$dep" ; then
+                        contains "$*" " $dep " || set -- "$* $dep"
+                    fi
+                done
         esac
+
+        # once all dependencies have been calculated, append the main package
+        set -- "$* $p"
+
+        # remove variables from the environment
+        unloadpkgfile
+    done
+
+    # now that we have the correct dependency-tree calculated,
+    # add all of the arguments
+    #
+    # splitting on '$@' is intentional for the loop
+    # shellcheck disable=SC2068
+    for p in $@ ; do
+        # start back at $WORK directory as $workdir may get deleted
+        cd "$WORK" || die "couldn't cd to $WORK"
+
+        # warn if package is being reinstalled
+        isinst "$p" && die "$p is already installed"
 
         # load package variables into the environment
         loadpkgfile "$p"
@@ -47,15 +84,33 @@ get() {
             *'://'*)
                 # must be a remote file
                 msg "downloading ${file##*/}"
-                outfile=$SOURCES/$pkgstring/${file##*/}
-                [ -f "$outfile" ] || dl "$file" >"$outfile"
-                chksum "$outfile" "$sum"
+
+# curl cannot handle '#' in file paths and I cannot figure
+# out how to fix this without patching it.
+#
+# as a shitty workaround use '-' as the delimitor for $SOURCES dirs
+IFS='#' read -r ppath pver <<EOF
+$SOURCES/$pkgstring
+EOF
+                outfile=$ppath-$pver/${file##*/}
+
+                if [ -f "$outfile" ] ; then
+                    # if file exists, it may be a partial download
+                    # try to continue the download
+                    if ! chksum "$outfile" "$sum" ; then
+                        dl "$file" "$outfile"
+                        chksum "$outfile" "$sum" || die 'checksum mismatch!'
+                    fi
+                else
+                    dl "$file" "$outfile"
+                    chksum "$outfile" "$sum" || die 'checksum mismatch!'
+                fi
                 extract "$outfile" "$workdir"
                 ;;
             *)
                 # no protocol specified, must be a local file.
                 # checksum it just as we would a remote file, then copy it
-                chksum "$portdir/$file" "$sum"
+                chksum "$portdir/$file" "$sum" || die 'checksum mismatch!'
                 # if file is in a dir, first create the dir
                 [ -d "$portdir/${file%%/*}" ] && mkdir -p "$workdir/${file%%/*}"
                 cp -f "$portdir/$file" "$workdir/$file"
@@ -63,9 +118,7 @@ get() {
     done <"$portdir"/sources
 }
 
-dl() {
-    curl -#fLC - --retry 3 -o - "$1"
-
+dl() { curl -#fLC - --retry 3 --create-dirs -o "$2" "$1" ; }
 # -*-* downloading with netcat currently work in progress -*-*-*
 # domain=${1#*://}
 # domain=${domain%%/*}
@@ -79,43 +132,3 @@ dl() {
 
 # EOF
 # -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
-}
-
-# args: $file $sum
-chksum() {
-    msg "comparing checksums for ${1##*/}"
-    sum=$(sha512sum "$1")
-    [ "$2" = "${sum%% *}" ] || die 'checksum mismatch!'
-}
-
-extract() {
-    case $1 in
-        *.tar.*|*.tgz|*.txz|*.tbz)
-            decompress "$1" | tar -C "$2" -xf -
-
-            # Ensure extracted tar files are in the top level of $2.
-            #
-            # note: Ee must use a loop here as glob will match '.'
-            #       in some shells even when not in the directory,
-            #       which will cause 'mv' to prematurely error.
-            for dot in "$2"/*/.* ; do
-                mv "$dot" "$2"/ 2>/dev/null ||:
-            done
-            mv "$2"/*/*  "$2"/ 2>/dev/null ||:
-
-            # remove any empty dirs we may have created
-            rmdir "$2"/* 2>/dev/null ||:
-            ;;
-        *.xz|*.gz|*.bz2)
-            out=${1##*/}
-            decompress "$1" >"$2/${out%.*}"
-    esac
-}
-
-decompress() {
-    case ${1##*.} in
-        xz|txz) xz -qdcT 0 ;;
-        gz|tgz) gunzip -qdc ;;
-        bz2|tbz) bunzip2 -qdc
-    esac <"$1"
-}
diff --git a/src/build b/src/build
--- a/src/build
+++ b/src/build
@@ -4,19 +4,34 @@
 
 run_build() {
     cd "$workdir" || die "couldn't cd to $workdir"
-    msg "building $name"
 
+    # load user and system flags into the environment
     getflags
 
-    # automatically find and apply patches if they exist
-    bspatch
+    # if pkgfile does not defined a prebuild() function,
+    # try to apply any patches that may exist (convenience)
+    if type prebuild >/dev/null 2>&1 ; then
+        prebuild || die "prebuild failed for $name"
+    else
+        bspatch
+    fi
+
+    msg "building $name"
 
     # if pkgfile has a build() function, execute it
     if type build >/dev/null 2>&1 ; then
-        build
+        build || die "build failed for $name"
     else
-        generic_build
-    fi || die "build failed for $name"
+        generic_build || die "generic build failed for $name"
+    fi
+
+    # run postbuild(), if defined
+    if type postbuild >/dev/null 2>&1 ; then
+        postbuild || die "postbuild failed for $name"
+    fi
+
+    # remove all suckage that gets put here. (ex: docs)
+    rm -r "${pkg:-?}"/sucks 2>/dev/null ||:
 
     # create pkg dir in case it hasn't be already
     # bonsai uses this directory as its pkg "database"
@@ -28,8 +43,7 @@ getflags() {
     # Import user's flags and export them.
     isinst @cfg >/dev/null && . "$CONFIG"/build.cfg
 
-    # If we're bootstrapping, we most likely will not
-    # yet have slibtool or pkgconf.
+    # Only use slibtool/pkgconf if we aren't bootstrapping.
     [ -x /bin/slibtool ] && LIBTOOL=/bin/slibtool
     [ -x /bin/pkgconf  ] && PKG_CONFIG=/bin/pkgconf
 
@@ -67,6 +81,9 @@ getflags() {
 
 # Try to automagically build/install if a pkgfile doesn't
 # define a custom build().  Works for most packages.
+#
+# sc bug, thinks we're using arguments yet we aren't passing any
+# shellcheck disable=SC2119
 generic_build() {
     if [ -f configure ] ; then
         bscfg || return 1
