src: add "$libs" variable to specify needed linked libraries at compile time, saves trouble with poorly written makefiles

diff --git a/src/add b/src/add
--- a/src/add
+++ b/src/add
@@ -60,6 +60,11 @@ add() {
         # load package variables into the environment
         loadpkgfile "$p"
 
+        # check if we have required libs to build
+        if [ "$libs" ] ; then
+            haslib "$libs" || die "missing required libraries to build"
+        fi
+
         # clear old working directory should it exist
         rm -rf -- "$workdir" 2>/dev/null ||:
         mkdir -p "$workdir"
