mass cleanup, restructuing, functionization - round 1
bug spotfix

diff --git a/src/addpkg b/src/addpkg
--- a/src/addpkg
+++ b/src/addpkg
@@ -1,7 +1,7 @@
 # vi:syntax=sh
 # shellcheck shell=sh
 
-# adds a port
+# downloads, builds, and installs a port
 # params: $name
 addpkg() {
     [ "$1" ] || die "addpkg(): no pkg given"
@@ -11,68 +11,6 @@ addpkg() {
         isinst "$pkg" > /dev/null &&
             die "port $pkg is already installed"
     done
-
-    # loads pkgfile for given $name
-    load_pkgfile() {
-        name="$1"
-        pkg="$pkgs"/"$name"
-        pkgfile="$ports/$name/pkgfile"
-        export pkg name pkgfile
-        [ -s "$pkgfile" ] || die "addpkg(): could not source $name's pkgfile"
-        . "$pkgfile"
-        ismetapkg "$name" && version=metapkg
-        pkgid="${name}${delim:=#}${version:=unknown}"
-        pkgworkdir="$work/$name"
-        export version source pkgid pkgworkdir
-    }
-
-    # unsets vars as not to persist from pkg to pkg
-    unload_pkgfile() {
-        unset name pkgfile pkgid version source depends deps \
-              md5 sha1 sha256 sha512 pkgworkdir nolink
-        unset -f prebuild build postbuild
-    }
-
-    # adds the given $name
-    add() {
-        ismetapkg "$1" || validate_gcc $1
-
-        # clear any work from previous build
-        rm -rf "${work:?}" 2>/dev/null ||:
-
-        load_pkgfile "$1"
-
-        if isinst "$name" >/dev/null ; then
-            msg "port $name is already installed"
-            unload_pkgfile
-            return 1
-        fi
-
-        # download / checksum / extract the package
-        get
-
-        # return if we've been instructed only to download the tarball
-        [ "$DLONLY" ] && return
-
-        if ! ismetapkg "$name" ; then
-            mkdir -p "$pkgs/$name"
-            trap 'rmdir $pkgs/$name' INT TERM
-        fi
-
-        run_build "$@" || die "$name failed to build"
-
-        if [ -d "$pkgs/$name" ] ; then
-            clear_junk "$name"
-            linkpkg "$name" || die "$name failed to link"
-        fi
-
-        add_db "$name" "$version"
-        msg "$name installed!"
-
-        clean
-        trap - INT TERM
-        unload_pkgfile
-    }
     
     # the packages asked to install
     main_packages="$*"
@@ -104,10 +42,80 @@ addpkg() {
     # prompt user for confirmation before continuing
     confirm || return 1
 
-    for pkg in $@ ; do
-        add "$pkg"
+    # main loop
+    for pkg_to_add in $@ ; do
+        # clear any work from previous build
+        rm -rf "${work:?}" 2>/dev/null ||:
+
+        # sanity check if not meta pkg
+        ismetapkg "$pkg_to_add" || validate_gcc "$pkg_to_add"
+
+        # load all pkgfile variables into environment
+        load_pkgfile "$pkg_to_add"
+
+        # check if is already installed
+        if isinst "$name" >/dev/null ; then
+            msg "port $name is already installed"
+            unload_pkgfile
+            continue
+        fi
+
+        # download / checksum / extract the package
+        get "$pkg_to_add"
+
+        # continue if we've been instructed only to download the tarball
+        [ "$DLONLY" ] && continue
+
+        # create $pkgdir directory
+        createpkgdir "$pkg_to_add" || die "failed to create $root/src/pkgs/$pkg_to_add"
+
+        # build
+        run_build || die "$pkg_to_add failed to build"
+
+        # link and install
+        installpkg "$pkg_to_add" || die "$pkg_to_add failed to install"
+
+        # unload as not to persist from pkg to pkg
+        unload_pkgfile
     done || die "failed to install $port"
 
     unset main_packages pkg dep
-    unset -f load_pkgfile unload_pkgfile prompt_user add
+    unset -f load_pkgfile unload_pkgfile prompt_user
+}
+
+# 1) create the $pkgdir if needed with given $name
+# 2) set a trap to remove it incase we are interrupted
+#    this trap is unset at the end of installpkg()
+# params: $name
+createpkgdir() {
+    if ! ismetapkg "$1" ; then
+        mkdir -p "$pkgs/$1"
+        trap 'rmdir $pkgs/$1' INT TERM
+    fi
+}
+
+# 1) cleans up package
+# 2) links it
+# 3) adds to the database
+# params: $name
+# assumes: all pkgfile vars in the environment
+installpkg() {
+    # check again incase we weren't called via addpkg()
+    if isinst "$1" >/dev/null ; then
+        msg "port $1 is already installed"
+        unload_pkgfile
+        return 1
+    fi
+
+    if [ -d "$pkgs/$1" ] ; then
+        clear_junk "$1"
+        linkpkg "$1" || die "$1 failed to link"
+    fi
+
+    add_db "$1" "$version"
+    msg "$1 installed!"
+
+    # clear $pkgs tree of empty dirs and removes $work
+    clean
+    trap - INT TERM
 }
diff --git a/src/build b/src/build
--- a/src/build
+++ b/src/build
@@ -3,8 +3,9 @@
 
 # runs build() method inside a pkgfile! -name readme 
 # params: none
+# asssumes: $pkgworkdir $name and all pkgfile vars in the environment
 run_build() { 
-    cd "$pkgworkdir" || die "build(): unable to cd to $work/$pkgid"
+    cd "$pkgworkdir" || die "build(): unable to cd to $pkgworkdir"
     msg "building $name..."
 
     getflags
@@ -70,8 +71,6 @@ getflags() {
 
 # convenience function, tries to find all *.patch
 # in the top-level $work/$name directory and apply them
-# note: -prune here is a more portable way of -maxdepth
-#       (sbase's find does not have -maxdepth)
 bonsai_patch() {
     find . ! -name . -prune -name "*.patch" | while read -r patch ; do
         { patch -p0 < "$patch" || return 1 ; } | msg
@@ -90,8 +89,6 @@ bonsai_configure() {
     fi
 
     ${nls:=false}   || _nls=--disable-nls
-    ${tests:=false} || _tests=--without-tests
-    ${debug:=false} || _debug='--disable-debug --disable-debugger'
     ${quiet:=false} && _quiet='--silent --quiet'
 
     if [ $FILE = configure ] ; then
@@ -112,8 +109,9 @@ bonsai_configure() {
                     --disable-rpath --disable-option-checking  --enable-fast-install \
                     --disable-dependency-tracking --without-ada --without-shared \
                     --disable-libtool-lock --disable-docs --disable-gtk-docs \
-                    --disable-gtk-docs-html --docdir=/dev/null \
-                    $_quiet $_debug $_nls $_tests -C ; do
+                    --disable-gtk-docs-html --docdir=/dev/null --without-tests \
+                    --disable-debug --disable-debugger \
+                    $_quiet $_nls -C ; do
 
             addflag $flag $flag &
         done
@@ -124,9 +122,8 @@ bonsai_configure() {
         addflag --disable-static --enable-static &
         addflag --enable-tests --disable-tests &
         addflag --with-shared --without-shared &
-        $debug || addflag --with-debug --without-debug &
-        $tests || addflag --with-tests --without-tests &
-        $tests && addflag --enable-extratests --enable-extratests &
+        addflag --with-debug --without-debug &
+        addflag --with-tests --without-tests &
         wait
 
         for flag in "$@" ; do
@@ -137,7 +134,7 @@ bonsai_configure() {
     ./$FILE $(shellcat "$tmp_flags") "$@" || die "$FILE failed for $name"
 
     unset -f addflag
-    unset flag tmp_help _nls _debug _quiet _tests FILE tmp
+    unset flag tmp_help _nls _quiet FILE tmp
 }
 
 bonsai_make() {
diff --git a/src/get b/src/get
--- a/src/get
+++ b/src/get
@@ -3,8 +3,9 @@
 
 # downloads url and extracts to $work/$pkg
 # params: none
-# assumes: $name $version $source $pkgid $pkgfile $pkgworkdir in environment
+# assumes: $version $source $pkgid $pkgfile $pkgworkdir in environment
 get() {
+    name="$1"
     dldir="$work/dl"
     mkdir -p "$pkgworkdir" "$dldir" "$sources"
 
@@ -48,43 +49,6 @@ get() {
         ${keep_tarballs:=true} && cp -f "$dldir/$pkgid$ext" "$sources"/
     }
 
-    # compares checksum for $archive and extracts to $pkgworkdir
-    # params: archive
-    extract() {
-        ismetapkg "$name" || verify_checksum "$1"
-        msg "extracting $name"...
-        decompress() {
-            case "${ext##*.}" in
-                xz)
-                    if type xz-embedded >/dev/null ; then
-                        xz-embedded < "$1"
-                    else
-                        xz -qdc "$1"
-                    fi
-                    ;;
-                gz|tgz) gunzip  -qdc  "$1" ;;
-                bz2)    bunzip2 -qdc  "$1" ;;
-                zip)    unzip   -qp   "$1" ;;
-            esac || die "get(): failed to decompress $1"
-        }
-        case "$ext" in
-            .tar.*|.tgz)
-                decompress "$1" | tar -C "$dldir" -xf - || die "failed to decompress $1"
-                # ensure files are in toplevel (ie $dir/name, not $dir/$name/$name)
-                mv "$dldir"/*/*  "$pkgworkdir"/
-                # copy any hidden files
-                find "$dldir" -name ".*" ! -name '.' | while read -r file ; do
-                    mv "$file" "$pkgworkdir"/
-                done
-                # try to remove possible empty dirs
-                rmdir "$dldir"/* 2>/dev/null ||:
-                rmdir "$dldir" 2>/dev/null ||:
-                ;;
-            # if not a tarball, simply write to $pkgworkdir
-            *) decompress "$1" > "$pkgworkdir/${1%%$ext}"
-        esac || die "get(): failed to extract $1"
-    }
-
     # do not try to dl / extract if metapkg or source=none
     if [ "$version" != metapkg ] && [ "$source" != none ] ; then
         # download tarball only if not in $sources
@@ -101,11 +65,12 @@ get() {
         cp -f "$file" "$pkgworkdir"/
     done
     unset dldir ext file
-    unset -f dlgit dlcurl extract decompress
+    unset -f dlgit dlcurl
 }
 
 # verifies hash of $tarball against hash in the pkgfile
 # params: $tarball
+# assumes: one of the following: sha{512,256,1} or md5 in the environment
 verify_checksum() {
     [ "$1" ] || die "verify_checksum(): no tarball provided"
 
@@ -138,4 +103,47 @@ verify_checksum() {
         printf "\n"
         die "checksum mismatch for $3"
     fi
+}
+
+# decompresses a given tarball to stdout
+decompress() {
+    case "${ext##*.}" in
+        xz|txz) 
+            if type xz-embedded >/dev/null ; then
+                xz-embedded < "$1"
+            else
+                xz -qdc "$1"
+            fi
+            ;;
+        gz|tgz)  gunzip  -qdc  "$1" ;;
+        bz2|tbz) bunzip2 -qdc  "$1" ;;
+        zip)     unzip   -qp   "$1" ;;
+    esac || die "get(): failed to decompress $1"
+}
+
+# compares checksum for given tarball and extracts to $pkgworkdir
+# params: tarball
+# assumes: 1. $name, $ext, $dldir, $pkgworkdir
+#          2. one of the following: sha{512,256,1} or md5 in the environment
+extract() {
+    ismetapkg "$name" || verify_checksum "$1"
+    msg "extracting $name..."
+    mkdir -p "$dldir" "$pkgworkdir"
+    case "$ext" in
+        .tar.*|.tgz)
+            decompress "$1" | tar -C "$dldir" -xf - || die "failed to decompress $1"
+            # ensure files are in toplevel (ie $dir/name, not $dir/$name/$name)
+            mv -f "${dldir:?}"/*/* "${pkgworkdir:?}"/
+            # copy any hidden files
+            find "$dldir" -name ".*" ! -name '.' | while read -r file ; do
+                mv "$file" "${pkgworkdir:?}"/
+            done
+            # try to remove possible empty dirs
+            rmdir "$dldir"/* 2>/dev/null ||:
+            rmdir "$dldir" 2>/dev/null ||:
+            ;;
+        # if not a tarball, simply write to $pkgworkdir
+        *) decompress "$1" > "${pkgworkdir:?}/${1%%$ext}"
+    esac || die "get(): failed to extract $1"
+    unset file
 }
