refactoring; gcc bootstrap with checks; make() bugfixes; safety checks; more

diff --git a/src/bore-addpkg b/src/bore-addpkg
--- a/src/bore-addpkg
+++ b/src/bore-addpkg
@@ -8,27 +8,29 @@ addpkg() {
     isinst $pkgname > /dev/null && die "port $pkgname is already installed"
 
     [ -f "$pkgfile" ] || die "addpkg(): could not source $pkgname's pkgfile"
-    . "$pkgfile"
+    name=$pkgname . "$pkgfile"
 
     [ -z "$version" ] && version='unknown'
 
     pkgid="${pkgname}${delim}${version}"
-    pkgdir="$work"/"$pkgid"
 
     get "$source" $pkgname "$version"
 
-    cd "$pkgdir" || die "addpkg(): unable to cd to $pkgdir"
+    cd "$work/$pkgid" || die "addpkg(): unable to cd to $work/$pkgid"
 
     msg "building $pkgname..."
     mkdir -p "$pkgs"/$pkgname
 
-    if run_build $pkgname ; then
-        sanity_check && rm -rf "$pkgdir"
-        link_pkg $pkgname
-        clear_junk $pkgname
-        add_db $pkgname $version
-        msg "$pkgname installed!"
-        clean
-    fi
-    unset pkgname pkgfile version pkgid pkgdir
+    run_build $pkgname || die "$pkgname failed to build"
+
+    sanity_check && rm -rf "$work/$pkgid"
+
+    link_pkg $pkgname || die "$pkgname failed to link"
+
+    clear_junk $pkgname
+    add_db $pkgname $version
+    msg "$pkgname installed!"
+    clean
+
+    unset pkgname pkgfile version pkgid
 }
diff --git a/src/bore-build b/src/bore-build
--- a/src/bore-build
+++ b/src/bore-build
@@ -1,10 +1,28 @@
 # runs build() method inside a pkgfile
 # params: pkgname
 run_build() {
-    set -e
     getcc
+
+    # if we're using pkg mgr's built in gcc, make sure its valid/existant
+    # if its not -- check to see if we're trying to download one
+    # ... if not, we cannot compile packages -- error out
+    if [ ! -x "$gcc" ] ; then
+        case $pkgname in
+            *gcc*) ;;
+            *tcc*) ;;
+            *) die "No compiler toolchain has yet been installed.
+         Try \`$PKG_MGR_NAME search gcc\` to find one."
+        esac
+    fi
+
     getflags
     GNU_sucks
+
+    # attach default includes/libs
+    # note: These cannot just go in $CFLAGS as CFLAGS 
+    #       could be overwritten in a makefile.
+    gcc="\"$gcc\" -I. -L. -I\"$root\"/include -L\"$root\"/lib $CFLAGS $LDFLAGS"
+    tcc="\"$tcc\" -I. -L. -I\"$root\"/include -L\"$root\"/lib -static -w"
 
     if defined prebuild ; then
         name=$1 prebuild || die "$1 prebuild() failed"
@@ -15,105 +33,115 @@ run_build() {
     if defined build ; then
         name=$1 build || die "$1 build() failed"
     else
-        name=$1 generic_build || die "$1 generic build() failed"
+        name=$1 generic_build || die "$1 generic_build() failed"
     fi
     # run user defined postbuild(), if exists
     if defined postbuild ; then
         name=$1 postbuild || die "$1 postbuild() failed"
     fi
-    set +e
 }
 
 # return $cc if not user specified
 getcc() { [ -z "$cc" ] && cc="$gcc" ; }
+
 # convenience function
 cc() { $cc "$@" ; }
 
-# macros for convenience when dealing with borked makefiles:
-# add includes/libs coming with pkg to search paths
-# params: none, but assumes being withinside $work/$pkgname
-include_pkg_headers() {
-    for dir in $(find . -type d) ; do
-        PKG_INCLUDES="$PKG_INCLUDES -I$dir"
-    done
-    CFLAGS="$CFLAGS $PKG_INCLUDES"
-    unset dir
-}
-link_pkg_libs() {
-    for dir in $(find . -type d) ; do
-        PKG_LIBS="$PKG_INCLUDES -L$dir"
-    done
-    LDFLAGS="$PKG_LIBS $LDFLAGS"
-    unset dir
-}
-
 getflags() {
-    # If we are bootstrapping, all of our created symlinks
-    # will be non-functional. This is because they will be
-    # pointing to, for example, "/lib" instead of "$chroot/lib".
-    # As a fix for this, we will find and include every $pkg/lib.
-    # if [ "$BOOTSTRAP" ] ; then
-    #     for pkg in $(ls "$pkgs") ; do
-    #         [ -d "$pkgs"/$pkg/lib ] &&
-    #             LDFLAGS="$LDFLAGS -L"$pkgs"/$pkg/lib"
-    #         if [ -d "$pkgs"/$pkg/include ] ; then
-    #             CFLAGS="$CFLAGS -I"$pkgs"/$pkg/include"
-    #         fi
-    #     done
-    # fi
-
     LDFLAGS="$LDFLAGS $ldflags"
     CFLAGS="$CFLAGS $cflags"
     CPPFLAGS="$CPPFLAGS $cppflags"
     CXXFLAGS="$CXXFLAGS $cxxflags"
     PKG_CONFIG="$pkgcfgflags"
-    unset pkg
+    PREFIX="$pkgs/$pkgname"
+    DESTDIR=""
+    BINDIR="$PREFIX/bin"
+    INCLUDEDIR="$PREFIX/include"
+    LIBDIR="$PREFIX/lib"
+    LIBEXECDIR="$PREFIX/libexec"
+    MANDIR="$PREFIX/share/man"
+    PRESERVEDIR="$root/var/preserve"
 }
 
 # convenience function, tries to find all *.patch
 # in $work/$pkgname directory and apply them
 patch() {
     find . -type f -name "*.patch" | while read -r patch ; do
-        command patch -p0 < "$patch"
+        command patch -p0 < "$patch" | msg
     done
     unset patch
 }
 
 configure() {
-    ! $docs  && _docs="--disable-docs \
-                             --disable-gtk-docs \
-                             --disable-gtk-docs-html"
-    ! $nls   && _nls='--disable-nls'
-    ! $debug && _debug='--disable-debug --disable-debugger'
+    ! $docs  && conf_docs="--disable-docs \
+                           --disable-gtk-docs \
+                           --disable-gtk-docs-html"
+    ! $nls   && conf_nls='--disable-nls'
+    ! $debug && conf_debug='--disable-debug --disable-debugger'
+    $quiet   && conf_quiet='--silent --quiet'
 
     # try to enable as many options as possible
     # if they are allowed in the configure script
     allowed=""
-    tmp_help=$(mktemp)
+    tmp_help=/tmp/$PKG_MGR_NAME-$$.tmp
     ./configure --help > $tmp_help
+
     for flag in --static --enable-static --enable-static-link \
                 --disable-rpath --disable-option-checking --without-tests \
-                $quiet $debug $_nls $_docs ; do
+                $conf_quiet $conf_debug $conf_nls $conf_docs ; do
         grep -- "$flag" $tmp_help > /dev/null && allowed="$allowed $flag"
     done
+
     if grep -- --enable-shared $tmp_help > /dev/null ; then
         allowed="$allowed --disable-shared"
     fi
+
     rm -f $tmp_help
 
-    CC="$cc" CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" CPPFLAGS="$CPPFLAGS" \
-        CXXFLAGS="$CXXFLAGS" PREFIX="$pkgs/$pkgname" prefix="$pkgs/$pkgname" \
-        ./configure --prefix="$pkgs/$pkgname" $allowed "$@" > /dev/null
-    unset allowed flag tmp_help _docs _nls _debug
+    CFLAGS="$CFLAGS" \
+    LDFLAGS="$LDFLAGS" \
+    CPPFLAGS="$CPPFLAGS" \
+    CXXFLAGS="$CXXFLAGS" \
+    CC="$cc" \
+    cc="$cc" \
+    DESTDIR="$DESTDIR"
+    PREFIX="$PREFIX" \
+    prefix="$PREFIX" \
+    BINDIR="$BINDIR" \
+    INCLUDEDIR="$INCLUDEDIR" \
+    LIBDIR="$LIBDIR" \
+    LIBEXECDIR="$LIBEXECDIR" \
+    MANDIR="$MANDIR" \
+    PRESERVEDIR="$PRESERVEDIR" \
+        ./configure --prefix="$PREFIX" $allowed "$@" > /dev/null
+
+    return $?
+    # unset allowed flag tmp_help conf_docs conf_nls conf_debug conf_quiet
 }
 
 make() {
-    ! $mans && _docs="MANPREFIX=/dev/null"
-    $quiet  && _quiet='-s'
-    CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" CPPFLAGS="$CPPFLAGS" CXXFLAGS="$CXXFLAGS" \
-        command make $makeflags -j$jobs $_docs $_quiet \
-        CC="$cc" PREFIX="$pkgs/$pkgname" prefix="$pkgs/$pkgname" "$@" > /dev/null
-    unset _docs _quiet
+    ! $mans && make_docs="MANPREFIX=/dev/null MANDIR=/dev/null"
+    $quiet  && make_quiet='-s'
+
+    CFLAGS="$CFLAGS" \
+    LDFLAGS="$LDFLAGS" \
+    CPPFLAGS="$CPPFLAGS" \
+    CXXFLAGS="$CXXFLAGS" \
+        command make $makeflags -j$jobs $make_docs $make_quiet \
+        CC="$cc" \
+        cc="$cc" \
+        DESTDIR="$DESTDIR" \
+        PREFIX="$PREFIX" \
+        prefix="$PREFIX" \
+        BINDIR="$BINDIR" \
+        INCLUDEDIR="$INCLUDEDIR" \
+        LIBDIR="$LIBDIR" \
+        LIBEXECDIR="$LIBEXECDIR" \
+        MANDIR="$MANDIR" \
+        PRESERVEDIR="$PRESERVEDIR" "$@" > /dev/null
+
+    return $?
+    # unset make_quiet make_docs
 }
 
 # run if pkgfile doesn't define a custom build()
diff --git a/src/bore-get b/src/bore-get
--- a/src/bore-get
+++ b/src/bore-get
@@ -5,19 +5,19 @@ get() {
     _url="$1"
     _pkgname=$2
     _version="$3"
-    _pkgdir="$work"/"$_pkgid"
     _pkgid="${_pkgname}${delim}${_version}"
-    tmp=$(mktemp -d)
+    tmpdir=/tmp/$PKG_MGR_NAME-$$.tmp
+    mkdir -p $tmpdir
 
     clean
-    mkdir -p "$_pkgdir" "$sources" "$work"/"$_pkgid"
+    mkdir -p "$sources" "$work"/"$_pkgid"
     cd "$sources"
 
     if [ "$_version" = git ] ; then
         if [ ! -d "$_pkgid" ] ; then
             msg "cloning $_url..."
-            git clone $git_opts "$_url" $tmp || die "get(): could not clone $_url"
-            mv -f "$tmp"/* "$work"/"$_pkgid"
+            git clone $git_opts "$_url" $tmpdir || die "get(): could not clone $_url"
+            mv -f "$tmpdir"/* "$work"/"$_pkgid"
             $keep_tarballs && cp -rf "$work"/"$_pkgid" "$sources"/"$_pkgid"
         else
             cp -rf "$sources"/"$_pkgid" "$work"
@@ -29,9 +29,9 @@ get() {
             curl -q -L -C - $curl_opts -o "$_pkgid" --url "$_url" ||
                 die "get(): could not download $_pkgname"
         fi
-        cp -f "$_pkgid" $tmp
+        cp -f "$_pkgid" $tmpdir
 
-        case $(file $tmp/*) in
+        case $(file $tmpdir/*) in
             *tgz*) ext=tgz   ;;
             *'gzip comp'*)  ext=gz    ;;
             *'bzip2 comp'*) ext=bz2   ;;
@@ -40,32 +40,35 @@ get() {
         esac
 
         # decompressors bug out if no extension...
-        mv -f $tmp/* $tmp/${_pkgname}.${ext}
+        mv -f $tmpdir/* $tmpdir/${_pkgname}.${ext}
 
-        msg "extracting $_pkgname"
+        msg "extracting $_pkgname"...
         case $ext in
-            xz)     xz      -d $tmp/* ;;
-            gz|tgz) gunzip  -d $tmp/* ;;
-            bz2)    bunzip2 -d $tmp/* ;;
+            xz)     xz      -d $tmpdir/* ;;
+            gz|tgz) gunzip  -d $tmpdir/* ;;
+            bz2)    bunzip2 -d $tmpdir/* ;;
             *) die "get(): unknown compression algorithm"
         esac
         [ $? -gt 0 ] && die "get(): failed to decompress $_pkgname"
 
-        if file $tmp/* | grep 'tar archive' > /dev/null ; then
+        if file $tmpdir/* | grep 'tar archive' > /dev/null ; then
             ext=tar.${ext}
-            mv $tmp/* $tmp/${_pkgname}.tar
-            tar -xf $tmp/${_pkgname}.tar -C $tmp/ || 
+            mv $tmpdir/* $tmpdir/${_pkgname}.tar
+            tar -xf $tmpdir/${_pkgname}.tar -C $tmpdir/ || 
                 die "get(): tar could not extract $_pkgid.$ext"       
         fi
 
         ! $keep_tarballs && rm -f "$sources"/"$_pkgid" 
 
-        mv -f $tmp/*/* "$work"/"$_pkgid" || die "get(): failed to move unpacked tarball"
+        mv -f $tmpdir/*/* "$work"/"$_pkgid" || die "get(): failed to move unpacked tarball"
     fi
+
     # copy all port's files, except its pkgfile -- (ex: patches)
-    for file in $(ls -A "$ports"/"$_pkgname"/* | grep -v pkgfile) ; do
-        cp -f "$file" "$_pkgdir"
+    ls -a "$ports"/"$_pkgname"/* | grep -v pkgfile | while read -r file ; do
+        cp -f "$file" "$work"/"$_pkgid"
     done
-    rm -rf $tmp
-    unset _url _pkgname _version _pkgid _pkgdir ext tmp file
+
+    rm -rf $tmpdir
+
+    unset _url _pkgname _version _pkgid ext tmpdir file
 }
