major refactorings ; getting ready for relaunch

diff --git a/src/bore-build b/src/bore-build
--- a/src/bore-build
+++ b/src/bore-build
@@ -1,28 +1,24 @@
 # runs build() method inside a pkgfile
-# params: none
+# params: pkgname
 run_build() {
     getcc
     getflags
     GNU_sucks
-    # run user defined prebuild(), if exists
+
     if defined prebuild ; then
-        prebuild || die "$name prebuild() failed"
+        name=$1 prebuild || die "$1 prebuild() failed"
     else # else, try to apply any patches (convenience)
-        patch || die "$name generic prebuild() failed"
+        patch || die "$1 generic prebuild() failed"
     fi
     # run user defined build(), if exists
     if defined build ; then
-        build || die "$name build() failed"
+        name=$1 build || die "$1 build() failed"
     else
-        { # if build() wasn't defined, try to build generically
-          [ -f configure ] && configure
-          make
-          make install
-        } || die "$name generic build() failed"
+        name=$1 generic_build || die "$1 generic build() failed"
     fi
     # run user defined postbuild(), if exists
     if defined postbuild ; then
-        postbuild || die "$name postbuild() failed"
+        name=$1 postbuild || die "$1 postbuild() failed"
     fi
 }
 
@@ -116,6 +112,13 @@ make() {
         command make $makeflags -j$jobs $_docs $_quiet \
         CC="$cc" PREFIX="$pkgs/$pkgname" prefix="$pkgs/$pkgname" "$@" > /dev/null
     unset _docs _quiet
+}
+
+# run if pkgfile doesn't define a custom build()
+generic_build() {
+    [ -f configure ] && configure
+    make
+    make install
 }
 
 # helper to get around all things that GNU does wrong with packaging
diff --git a/src/bore-utils b/src/bore-utils
--- a/src/bore-utils
+++ b/src/bore-utils
@@ -1,10 +1,10 @@
-msg()  { echo "$prompt $@" ; }
-die()  { >&2 msg Error "$@" ; exit 1 ; }
-warn() { >&2 msg Warning "$@" ; }
+msg()  { printf "%b\n" "$prompt $@" ; }
+die()  { >&2 msg "Error: $@" ; exit 1 ; }
+warn() { >&2 msg "Warning: $@" ; }
 
 usage() {
 cat << EOF
-$0 pkg mgr
+$PKG_MGR_NAME pkg mgr
 
 commands:
 -----------
@@ -30,7 +30,7 @@ defined() {
 # params: $command_name(s)
 has() { 
     for arg ; do
-        type arg || return 1
+        type $arg || return 1
     done > /dev/null
     unset arg
 }
@@ -54,6 +54,10 @@ test_link() {
         return 1
     fi
 }
+
+# posix shell utilities to commonly missing programs
+basename() { printf "%s" "${1##*/}" ; }
+tac() { printf "%s" "$@" | sed '1!G;h;$!d' ; }
 
 # cleans $pkgs tree of empty dirs and clears $work
 # params: none
@@ -79,11 +83,28 @@ sanity_check() {
     [ "$gcc" ]      || warn "\$gcc is not set"
     [ "$tcc" ]      || warn "\$tcc is not set"
     [ "$jobs" ]     || jobs=1
-
     for var in "$root" "$borehome" "$pkgs" "$ports" "$sources" "$work" ; do
         if [ -z "$var" ] || [ "$var" = / ] ; then
             die "config is not sane!"
         fi
     done
-    unset var
+    for dir in "$borehome" "$pkgs" "$ports" "$sources" "$work" ; do
+        [ ! -d "$dir" ] && mkdir "$dir"
+    done
+    unset var dir
+}
+
+# check if all dependencies are met on startup
+check_deps() {
+    for prog in cat cp find grep ln ls mkdir mv rm rmdir \
+                sort sed tar wc file gcc make ; do
+        has $prog || die "required program $prog is not available"
+    done
+    for prog in gzip bzip2 xz ; do
+        has $prog || warn "$prog is not installed. Some ports may not extract."
+    done
+    has git || warn "git is not installed. Some ports may not download."
+    has curl || warn "curl is not installed. Some ports may not download."
+    has patch || warn "patch is not installed. Some ports may not compile."
+    unset prog
 }
