non-chroot bore system now working

diff --git a/src/bore-addpkg b/src/bore-addpkg
--- a/src/bore-addpkg
+++ b/src/bore-addpkg
@@ -7,7 +7,8 @@ addpkg() {
     pkgfile="$ports"/$pkgname/pkgfile
     isinst $pkgname > /dev/null && die "port $pkgname is already installed"
 
-    . "$pkgfile" || die "addpkg(): can't source $pkgname's pkgfile?"
+    [ -f "$pkgfile" ] || die "addpkg(): could not source $pkgname's pkgfile"
+    . "$pkgfile"
 
     [ -z "$version" ] && version='unknown'
 
@@ -29,7 +30,7 @@ addpkg() {
         msg "$pkgname installed!"
         clean
     fi
-    unset pkg{name,file,dir,id}
+    unset pkgname pkgfile version pkgid pkgdir
 }
 
 # create symlinks for a port
@@ -37,39 +38,35 @@ addpkg() {
 link_pkg() {
     sanity_check
     pkgname=$1
-    cd "$borehome"
-    cd ..
+    cd "$root"
     msg 'creating symlinks...'
     for dir in bin sbin share include etc lib libexec ; do
         # recursively create pkg subdirectories in
         # equivalent /root subdirectories
-        # example: $pkgname/lib/pkgconfig -> /lib/pkgconfig
+        # example: $pkgname/lib/pkgconfig -> $root/lib/pkgconfig
         find "$pkgs"/$pkgname/$dir ! -path "*$dir" ! -path "*share/*man*" \
-            -type d 2> /dev/null | while read -r subdir ; do
+                -type d 2> /dev/null | while read -r subdir ; do
             mkdir -p "${subdir#$pkgs/$pkgname/}"
         done
         # recursively link all files
-        # example: $pkgname/include/asm/*.h -> /include/asm/*.h
+        # example: $pkgname/include/asm/*.h -> $root/include/asm/*.h
         find "$pkgs"/$pkgname/$dir ! -path "*share/*man*" \
             -type f -o -type l 2> /dev/null | while read -r file ; do
             file="${file#$pkgs/$pkgname/}"
 
-            # BUG: important: this is /src/pkgs not $pkgs for
-            #      now until I find a pathing fix!
-            # ln -sf "/src/pkgs/$pkgname/$file" ./$file
+            # BUG: how to fix this when bootstrapping...
             ln -sf "$pkgs/$pkgname/$file" ./$file
-
         done
     done
     $mans && # only link mans if config boolean is true
     if [ -d "$pkgs"/$pkgname/share/man ] ; then
-        for manX in $(seq -f "man%g" -s " " 1 8) ; do
+        seq -f "man%g" -s " " 1 8 | while read -r manX ; do
             find "$pkgs"/$pkgname/share/man/$manX \
-                ! -path "*/$manX" 2> /dev/null | while read -r man ; do
-                man="${man#$pkgs/$pkgname/}"
-                ln -sf "/src/pkgs/$pkgname/share/man/$manX/${man##*/}" "$man"
+                    ! -path "*/$manX" 2> /dev/null | while read -r man ; do
+                ln -sf "$pkgs/$pkgname/share/man/$manX/${man##*/}" \
+                    "${man#$pkgs/$pkgname/}"
             done
         done
     fi
-    unset pkgname dir subdir file manX man
+    unset dir subdir file manX man
 }
diff --git a/src/bore-get b/src/bore-get
--- a/src/bore-get
+++ b/src/bore-get
@@ -10,7 +10,7 @@ get() {
     tmp=$(mktemp -d)
 
     clean
-    mkdir -p "$_pkgdir" "$sources"
+    mkdir -p "$_pkgdir" "$sources" "$work"/"$_pkgid"
     cd "$sources"
 
     if [ "$_version" = git ] ; then
@@ -42,6 +42,7 @@ get() {
         # decompressors bug out if no extension...
         mv -f $tmp/* $tmp/${_pkgname}.${ext}
 
+        msg "extracting $_pkgname"
         case $ext in
             xz)     xz      -d $tmp/* ;;
             gz|tgz) gunzip  -d $tmp/* ;;
@@ -59,13 +60,12 @@ get() {
 
         ! $keep_tarballs && rm -f "$sources"/"$_pkgid" 
 
-        mv -f $tmp/*/* "$work"/"$_pkgid" ||
-            die "get(): failed to move unpacked tarball"
+        mv -f $tmp/*/* "$work"/"$_pkgid" || die "get(): failed to move unpacked tarball"
     fi
-    rm -rf $tmp
     # copy all port's files, except its pkgfile -- (ex: patches)
     for file in $(ls -A "$ports"/"$_pkgname"/* | grep -v pkgfile) ; do
         cp -f "$file" "$_pkgdir"
     done
+    rm -rf $tmp
     unset _url _pkgname _version _pkgid _pkgdir ext tmp file
 }
