refactorings; safety checks; bugfixes

diff --git a/src/bore-addpkg b/src/bore-addpkg
--- a/src/bore-addpkg
+++ b/src/bore-addpkg
@@ -1,73 +1,73 @@
 # adds a port
 # params: $pkgname
 addpkg() {
-    name=$1
-    pkgfile="$ports"/$name/pkgfile
+    [ "$(ls $ports | wc -l)" -gt 0 ] || die "addpkg(): no ports found"
 
-    if [ -f "$pkgfile" ] ; then
-        . "$pkgfile"
-    else
-        die "Error: can't source $name's pkgfile?"
-    fi
-    [ "$(ls $ports | wc -l)" -gt 0 ] || die "no ports found"
-    isinst $name > /dev/null && die "port $name is already installed"
+    pkgname=$1
+    pkgfile="$ports"/$pkgname/pkgfile
+    isinst $pkgname > /dev/null && die "port $pkgname is already installed"
 
-    [ -z "$version" ] && version='1.0'
-    pkgid="${name}${delim}${version}"
+    . "$pkgfile" || die "addpkg(): can't source $pkgname's pkgfile?"
+
+    [ -z "$version" ] && version='unknown'
+
+    pkgid="${pkgname}${delim}${version}"
     pkgdir="$work"/"$pkgid"
 
-    # download/extract package
-    get "$source"
-    cd "$pkgdir" || die "Error: unable to cd to $pkgdir"
+    get "$source" $pkgname "$version"
 
-    echo ". building $name..."
-    mkdir -p $opt/$name
+    cd "$pkgdir" || die "addpkg(): unable to cd to $pkgdir"
+
+    msg "building $pkgname..."
+    mkdir -p "$pkgs"/$pkgname
 
     if run_build ; then
-        rm -rf "$pkgdir"
-        link_pkg $name
-        clear_junk $name
-        add_db $name $version
-        echo "$name installed!"
+        sanity_check && rm -rf "$pkgdir"
+        link_pkg $pkgname
+        clear_junk $pkgname
+        add_db $pkgname $version
+        msg "$pkgname installed!"
         clean
     fi
+    unset pkg{name,file,dir,id}
 }
 
 # create symlinks for a port
 # params: $pkgname
 link_pkg() {
-    local pkgname=$1
-    cd "$src"
+    pkgname=$1
+    cd "$borehome"
     cd ..
-    echo '. creating symlinks...'
+    msg 'creating symlinks...'
     for dir in bin sbin share include etc lib libexec ; do
         # recursively create pkg subdirectories in
         # equivalent /root subdirectories
-        # example: $pkg/lib/pkgconfig -> /lib/pkgconfig
-        find "$opt"/$pkgname/$dir ! -path "*$dir" \
-            ! -path "*share/*man*" -type d 2> /dev/null | \
-                while read -r subdir ; do
-            mkdir -p "${subdir#$opt/$pkgname/}"
+        # example: $pkgname/lib/pkgconfig -> /lib/pkgconfig
+        find "$pkgs"/$pkgname/$dir ! -path "*$dir" ! -path "*share/*man*" \
+            -type d 2> /dev/null | while read -r subdir ; do
+            mkdir -p "${subdir#$pkgs/$pkgname/}"
         done
         # recursively link all files
-        # example: $pkg/include/asm/*.h -> /include/asm/*.h
-        find "$opt"/$pkgname/$dir ! -path "*share/*man*" \
-            -type f -o -type l 2> /dev/null | \
-                while read -r file ; do
-            file="${file#$opt/$pkgname/}"
-            # important: this is /opt not $opt !
-            ln -sf "/opt/$pkgname/$file" ./$file
+        # example: $pkgname/include/asm/*.h -> /include/asm/*.h
+        find "$pkgs"/$pkgname/$dir ! -path "*share/*man*" \
+            -type f -o -type l 2> /dev/null | while read -r file ; do
+            file="${file#$pkgs/$pkgname/}"
+
+            # BUG: important: this is /src/pkgs not $pkgs for
+            #      now until I find a pathing fix!
+            ln -sf "/src/pkgs/$pkgname/$file" ./$file
+
         done
     done
     $mans && # only link mans if config boolean is true
-    if [ -d "$opt"/$pkgname/share/man ] ; then
+    if [ -d "$pkgs"/$pkgname/share/man ] ; then
         for manX in $(seq -f "man%g" -s " " 1 8) ; do
-            find "$opt"/$pkgname/share/man/$manX \
-                ! -path "*/$manX" 2> /dev/null | \
-                    while read -r man ; do
-                man="${man#$opt/$pkgname/}"
-                ln -sf "/opt/$pkgname/share/man/$manX/${man##*/}" "$man"
+            find "$pkgs"/$pkgname/share/man/$manX \
+                ! -path "*/$manX" 2> /dev/null | while read -r man ; do
+                man="${man#$pkgs/$pkgname/}"
+                ln -sf "/src/pkgs/$pkgname/share/man/$manX/${man##*/}" "$man"
             done
         done
     fi
+    unset pkgname dir subdir file manX man
 }
diff --git a/src/bore-get b/src/bore-get
--- a/src/bore-get
+++ b/src/bore-get
@@ -1,43 +1,46 @@
 # downloads a given url and extracts to $work
+# params: $url, $pkgname, $version
 get() {
-    [ $# -lt 1 ] && die 'get(): no source given'
-    clean # clean $work, incase bore was interrupted
-    local url="$1"
-    local tmp=$(mktemp -d)
+    [ $# -lt 3 ] && die 'get(): insufficient arguments'
+    _url="$1"
+    _pkgname=$2
+    _version="$3"
+    _pkgdir="$work"/"$_pkgid"
+    _pkgid="${_pkgname}${delim}${_version}"
+    tmp=$(mktemp -d)
 
-    mkdir -p "$pkgdir" "$sources"
+    clean
+    mkdir -p "$_pkgdir" "$sources"
     cd "$sources"
 
-    if [ "$version" = git ] ; then
-        if [ ! -d "$pkgid" ] ; then
-            echo ". cloning $1..."
-            git clone $git_opts "$url" $tmp || die "get(): could not clone $url"
-            mv -f "$tmp"/* "$work"/"$pkgid"
-            $keep_tarballs && cp -rf "$work"/"$pkgid" "$sources"/"$pkgid"
+    if [ "$_version" = git ] ; then
+        if [ ! -d "$_pkgid" ] ; then
+            msg "cloning $_url..."
+            git clone $git_opts "$_url" $tmp || die "get(): could not clone $_url"
+            mv -f "$tmp"/* "$work"/"$_pkgid"
+            $keep_tarballs && cp -rf "$work"/"$_pkgid" "$sources"/"$_pkgid"
         else
-            cp -rf "$sources"/"$pkgid" "$work"
+            cp -rf "$sources"/"$_pkgid" "$work"
         fi
     else # we are downloading with curl
 
-        if [ ! -f "$pkgid" ] ; then
-            echo ". downloading $1..."
-            curl -q -L -C - $curl_opts -o "$pkgid" --url "$url" ||
-                die "get(): could not download $name"
-            cp -f "$pkgid" $tmp
-        else
-            cp -f "$pkgid" $tmp
+        if [ ! -f "$_pkgid" ] ; then
+            msg "downloading $_url..."
+            curl -q -L -C - $curl_opts -o "$_pkgid" --url "$_url" ||
+                die "get(): could not download $_pkgname"
         fi
+        cp -f "$_pkgid" $tmp
 
         case $(file $tmp/*) in
-            *tgz*)   local ext=tgz   ;;
-            *'gzip comp'*)  local ext=gz    ;;
-            *'bzip2 comp'*) local ext=bz2   ;;
-            *'XZ comp'*)    local ext=xz    ;;
-            *) die "get(): could not discern compression type of $name"
+            *tgz*) ext=tgz   ;;
+            *'gzip comp'*)  ext=gz    ;;
+            *'bzip2 comp'*) ext=bz2   ;;
+            *'XZ comp'*)    ext=xz    ;;
+            *) die "get(): could not discern compression type of $_pkgname"
         esac
 
         # decompressors bug out if no extension...
-        mv -f $tmp/* $tmp/${name}.${ext}
+        mv -f $tmp/* $tmp/${_pkgname}.${ext}
 
         case $ext in
             xz)     xz      -d $tmp/* ;;
@@ -45,23 +48,24 @@ get() {
             bz2)    bunzip2 -d $tmp/* ;;
             *) die "get(): unknown compression algorithm"
         esac
-        [ $? -gt 0 ] && die "get(): failed to decompress $name"
+        [ $? -gt 0 ] && die "get(): failed to decompress $_pkgname"
 
         if file $tmp/* | grep 'tar archive' > /dev/null ; then
             ext=tar.${ext}
-            mv $tmp/* $tmp/${name}.tar
-            tar -xf $tmp/${name}.tar -C $tmp/ || 
-                die "get(): tar could not extract $pkgid.$ext"       
+            mv $tmp/* $tmp/${_pkgname}.tar
+            tar -xf $tmp/${_pkgname}.tar -C $tmp/ || 
+                die "get(): tar could not extract $_pkgid.$ext"       
         fi
 
-        ! $keep_tarballs && rm -f "$sources"/"$pkgid" 
+        ! $keep_tarballs && rm -f "$sources"/"$_pkgid" 
 
-        mv -f $tmp/*/* "$work"/"$pkgid" ||
+        mv -f $tmp/*/* "$work"/"$_pkgid" ||
             die "get(): failed to move unpacked tarball"
     fi
     rm -rf $tmp
-    # copy all port's files, except its pkgfile
-    for file in $(ls -A "$ports"/"$name"/* | grep -v pkgfile) ; do
-        cp -f "$file" "$pkgdir"
+    # copy all port's files, except its pkgfile -- (ex: patches)
+    for file in $(ls -A "$ports"/"$_pkgname"/* | grep -v pkgfile) ; do
+        cp -f "$file" "$_pkgdir"
     done
+    unset _url _pkgname _version _pkgid _pkgdir ext tmp file
 }
diff --git a/src/bore-main b/src/bore-main
--- a/src/bore-main
+++ b/src/bore-main
@@ -1,13 +1,27 @@
-# default variables
-BOOTSTRAP=false
+check_deps() {
+    for prog in cat cp find grep ln ls mkdir mv rm rmdir \
+                sort sed tar wc file gcc make ; do
+        has $prog || die "required program $prog is not available"
+    done
+    for prog in gzip bzip2 xz ; do
+        has prog || warn "$prog is not installed. Some ports may not extract."
+    done
+    has git || warn "git is not installed. Some ports may not download."
+    has curl || warn "curl is not installed. Some ports may not download."
+    has patch || warn "patch is not installed. Some ports may not compile."
+    unset prog
+}
 
 main() {
+    check_deps
+
     case "$1" in
         *skeleton) shift ; create_skeleton_config "$1" ; exit ;;
         *bootstrap) BOOTSTRAP=true ; shift ;;
         --config=*) config="${1#--config=}" ; shift ;;
         --root=*) _root="${1#--root=}" ; shift ;;
         --gcc=*) _gcc="${1#--cc=}" ; shift ;;
+        *help|-h)  usage ;;
     esac
 
     loadconfig "$@"
@@ -20,7 +34,6 @@ main() {
             isinst|-i) isinst $2 ; exit $? ;;
             list|-l)   cat "$boredb" ; exit ;;
             count|-c)  cat "$boredb" | wc -l | sed 's/ //' ; exit ;;
-            *help|-h)  usage ;;
             *) if [ "$1" ] ; then
                    addpkg $1
                    exit $?
