rework main; loadconfig

diff --git a/src/bore-config b/src/bore-config
--- a/src/bore-config
+++ b/src/bore-config
@@ -1,36 +1,32 @@
 loadconfig() {
-    for arg in "$@" ; do
-        case "$arg" in
-            --config=*) config="${arg#--config=}" ;;
-            --root=*) chroot_root="${arg#--root=}" ;;
-            --cc=*)   bootstrap_cc="${arg#--cc=}" ;;
-            --*skeleton) return;
-        esac
-    done
-
-    if [ -n "$config" ] ; then
-        . "$config"
-    elif [ -z "$chroot_root" ] ; then
-        . /src/bore.rc || die "Error: Could not source /src/bore.rc"
-    else
-        tmp=$(mktemp)
-        sed "s|^root=.*|root=$chroot_root|" "$chroot_root"/src/bore.rc > "$tmp"
-        . "$tmp"
-        rm -f "$tmp"
+    if [ "$config" ] ; then
+        borerc="$config"
+    elif [ -f ${HOME}/.local/$0/src/$0.rc ] ; then
+        borerc="${HOME}/.local/$0/src/$0.rc"
+    elif [ -f /src/$0.rc ] ; then
+        borerc="/src/$0.rc"
     fi
+    . "$borerc" || die "loadconfig(): could not source config"
 
-    [ -z "$jobs" ] && jobs=1
+    [ "$_root" ] && root="$_root"
+    [ "$_gcc" ] && gcc="$_gcc"
+
     update_db
     check_vars
 }
 
 check_vars() {
-    [ "$root" ]   || die "loadconfig(): \$root failed to set"
-    [ "$src" ]    || die "loadconfig(): \$src failed to set"
-    [ "$opt" ]    || die "loadconfig(): \$opt failed to set"
-    [ "$bore" ]   || die "loadconfig(): \$bore failed to set"
-    [ "$boredb" ] || die "loadconfig(): \$boredb failed to set"
-    [ "$delim" ]  || die "loadconfig(): \$delim failed to set"
+    [ "$root" ]     || die "loadconfig(): \$root failed to set"
+    [ "$borehome" ] || die "loadconfig(): \$borehome failed to set"
+    [ "$boredb" ]   || die "loadconfig(): \$boredb failed to set"
+    [ "$pkgs" ]     || die "loadconfig(): \$pkgs failed to set"
+    [ "$ports" ]    || die "loadconfig(): \$ports failed to set"
+    [ "$sources" ]  || die "loadconfig(): \$sources failed to set"
+    [ "$work" ]     || die "loadconfig(): \$work failed to set"
+    [ "$delim" ]    || die "loadconfig(): \$delim failed to set"
+    [ "$gcc" ]      || warn "loadconfig(): \$gcc failed to set"
+    [ "$tcc" ]      || warn "loadconfig(): \$tcc failed to set"
+    [ "$jobs" ]     || jobs=1
 }
 
 # creates a skeleton config
@@ -44,12 +40,13 @@ create_skeleton_config() {
         fi
     else
         path='.'
+        mkdir -p ${HOME}/.local/$0/src
+        msg "creating skeleton config \~/.local/$0/${0}"
     fi
-cat > "$path"/bore.rc.skel << "EOF"
+cat > "$path"/$0.rc.skel << "EOF"
 # bore variables
 root=${HOME}/.local/bore
-borehome="$root"/bore
-borerc="$borehome"/bore.rc
+borehome="$root"/src
 boredb="$borehome"/bore.db
 pkgs="$borehome"/pkgs
 ports="$borehome"/ports
@@ -75,13 +72,12 @@ git_opts='-q --progress --depth 1'
 keep_tarballs=true
 
 # options
-mans=true  # install man pages?
-docs=false # install extra documentation?
-nls=false  # provide native-language-support?
-quiet=true # configure/make silently?
+mans=true   # install man pages?
+docs=false  # install extra documentation?
+nls=false   # provide native-language-support?
+quiet=true  # configure/make silently?
 debug=false # compile in debugging tools/information?
-
-# package/version delimiter
-delim='-'
+prompt='→ ' # msg prompt
+delim='-'   # package/version delimiter
 EOF
 }
