various bugfixes, small improvements
tabs->spaces fixup

diff --git a/src/bore-build b/src/bore-build
--- a/src/bore-build
+++ b/src/bore-build
@@ -41,28 +41,27 @@ run_build() {
 
 # convenience functions
 cc() { $cc "$@" ; }
-gcc() { $_gcc "$@" ; }
+gcc() { $gcc "$@" ; }
 # tcc() { $_tcc "$@" ; }
 
 getflags() {
+    LIBRARY_PATH="$root/lib:$root/libexec:$LIBRARY_PATH"
+    C_INCLUDE_PATH="$root/include:$C_INCLUDE_PATH"
     CFLAGS="-I. -L. -I$root/include -L$root/lib -B$root/libexec $CFLAGS $cflags"
-    LDFLAGS="$LDFLAGS $ldflags"
-    CPPFLAGS="$CPPFLAGS $cppflags"
-    CXXFLAGS="$CXXFLAGS $cxxflags"
+    LDFLAGS="-L. $LDFLAGS $ldflags"
+    CPPFLAGS="-I. -I$root/include $CPPFLAGS $cppflags"
+    CXXFLAGS="-I. $CXXFLAGS $cxxflags"
     PKG_CONFIG="$pkgcfgflags"
     PREFIX="$pkgs/$pkgname"
-    DESTDIR=""
+    DESTDIR=''
     BINDIR="$PREFIX/bin"
     INCLUDEDIR="$PREFIX/include"
     LIBDIR="$PREFIX/lib"
     LIBEXECDIR="$PREFIX/libexec"
     MANDIR="$PREFIX/share/man"
     PRESERVEDIR="$root/var/preserve"
-
-    _gcc="$gcc $CFLAGS"
-
-    [ -z "$cc" ] && cc="$_gcc"
-    CC="$cc"
+    cc="${cc:=$gcc}"
+    CC="${cc:=$cc}"
 }
 
 # convenience function, tries to find all *.patch
@@ -102,7 +101,7 @@ configure() {
 
         for flag in --static --enable-static --enable-static-link \
                     --disable-rpath --disable-option-checking --without-tests \
-                    --disable-dependency-tracking --without-ada \
+                    --disable-dependency-tracking --without-ada --without-shared \
                     $conf_quiet $conf_debug $conf_nls $conf_docs ; do
             grep -- "$flag" $tmp_help > /dev/null && allowed="$allowed $flag"
         done
@@ -116,10 +115,11 @@ configure() {
         grep -- --with-tests $tmp_help > /dev/null &&
             allowed="$allowed --without-tests"
 
-
         rm -f $tmp_help
     fi
 
+    LIBRARY_PATH="$LIBRARY_PATH" \
+    C_INCLUDE_PATH="$C_INCLUDE_PATH" \
     CFLAGS="$CFLAGS" \
     LDFLAGS="$LDFLAGS" \
     CPPFLAGS="$CPPFLAGS" \
@@ -135,8 +135,9 @@ configure() {
     LIBEXECDIR="$LIBEXECDIR" \
     MANDIR="$MANDIR" \
     PRESERVEDIR="$PRESERVEDIR" \
-        ./$FILE $allowed "$@" > /dev/null 
-    # --prefix="$PREFIX" 
+        ./$FILE $([ $FILE = configure ] && echo --prefix="$PREFIX") \
+        $allowed "$@"
+        # > /dev/null 
     # NOTE: some autogen won't allow '--prefix=', fix later
 
     return $?
@@ -152,8 +153,10 @@ make() {
     CPPFLAGS="$CPPFLAGS" \
     CXXFLAGS="$CXXFLAGS" \
         command make $makeflags -j$jobs $make_docs $make_quiet \
-        CC="$cc" \
-        cc="$cc" \
+        CC="$CC" \
+        cc="$CC" \
+        LIBRARY_PATH="$LIBRARY_PATH" \
+        C_INCLUDE_PATH="$C_INCLUDE_PATH" \
         DESTDIR="$DESTDIR" \
         PREFIX="$PREFIX" \
         prefix="$PREFIX" \
@@ -179,6 +182,14 @@ generic_build() {
 
 # helper to get around all things that GNU does wrong with packaging
 GNU_sucks() {
+    # GNU programs have the most insane dependency tracking I have ever seen.
+    # To check for dependencies, they often simply try to run the program
+    # and if it has a -gt 0 exit code, the dependency must not be in $PATH.
+    #
+    # This breaks all kinds of things, namely if we are running under `set -e`
+    # As a workaround, just manually track depedencies -- clear the file.
+    [ -f build-aux/missing ] && :> build-aux/missing
+
     # Some GNU makefiles test certain program flags to see if they
     # are GNU coreutils programs. Some of our minimal programs fail this,
     # causing the makefile to abort unless $ENV variables are set. Absurd.
