improve dependency handling

diff --git a/src/bore-addpkg b/src/bore-addpkg
--- a/src/bore-addpkg
+++ b/src/bore-addpkg
@@ -1,10 +1,13 @@
 # adds a port
 # params: $name
 addpkg() {
+    [ "$1" ] || die "addpkg(): no pkg given"
     is_empty "$ports" && die "addpkg(): no ports found"
 
-    isinst "$1" > /dev/null &&
-        die "port $1 is already installed"
+    for pkg in "$@" ; do
+        isinst "$pkg" > /dev/null &&
+            die "port $pkg is already installed"
+    done
 
     # check if gcc is functional
     validate_gcc
@@ -32,7 +35,7 @@ addpkg() {
         # prompt user before continuing
         warn "these packages will be installed:"
         # note: $dep_needed is padded by spaces
-        printf "\n  %s\n\n" "$main_package$deps_needed"
+        printf "\n  %s\n\n" "$main_packages$deps_needed"
         if [ -z "$NO_PROMPT" ] ; then
             msg_no_nl "continue? (y/n): "
             read -r ans
@@ -85,27 +88,30 @@ addpkg() {
         unload_pkgfile
     }
 
-    # grab initial package variables
-    load_pkgfile "$1"
+    for pkg in "$@" ; do
+        # grab initial package variables
+        load_pkgfile "$pkg"
 
-    # the package we will install
-    main_package="$name"
+        # the packages we will install
+        main_packages="$main_packages $name"
 
-    # search for dependencies of the initial package
-    # the value is stored in $pkgdeps
-    pkgdeps "$name"
+        # search for dependencies of the initial package
+        # the value is stored in $pkgdeps
+        pkgdeps "$name"
 
-    # add any deps to $deps_needed
-    case "$pkgdeps" in
-        # if deps is unset or empty string, there are no deps
-        "") ;;
-        "* *") ;;
-        *) 
-            for dep in $pkgdeps ; do
-                isinst "$dep" > /dev/null || 
-                    deps_needed="$deps_needed $dep"
-            done
-    esac
+        # add any deps to $deps_needed
+        case "$pkgdeps" in
+            # if deps is unset or empty string, there are no deps
+            "") ;;
+            "* *") ;;
+            *) 
+                for dep in $pkgdeps ; do
+                    isinst "$dep" > /dev/null || 
+                        deps_needed="$deps_needed $dep"
+                done
+        esac
+        unload_pkgfile
+    done
 
     # prompt before continuing
     prompt_user || return 1
@@ -113,10 +119,12 @@ addpkg() {
     # add deps
     for port in $deps_needed ; do
         add "$port"
-    done || die "failed to install deps required by $main_package"
+    done || die "failed to install deps required by $main_packages"
 
     # add package
-    add "$main_package"
+    for pkg in $main_packages ; do
+        add "$pkg"
+    done
 
     unset -f load_pkgfile unload_pkgfile prompt_user add
 }
