updates on rewrite

diff --git a/src/build b/src/build
--- a/src/build
+++ b/src/build
@@ -1,18 +1,20 @@
+# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
+# build                  http://github.com/bonsai-linux/bonsai
+# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 # vi:syntax=sh
 # shellcheck shell=sh
+# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 
-# runs build() method inside a pkgfile! -name readme 
-# params: none
-# asssumes: $pkgworkdir $name and all pkgfile vars in the environment
+# runs build() method inside a pkgfile
 run_build() { 
     cd "$pkgworkdir" || die "build(): unable to cd to $pkgworkdir"
     msg "building $name..."
 
-    # export all our flags to the environment
     getflags
 
-    # workarounds for packaging that sucks
-    sucks
+    # manually track configure dependencies
+    [ -f missing ] && :>missing
+    [ -f build-aux/missing ] && :>build-aux/missing
 
     if defined prebuild ; then
         prebuild || die "$name prebuild() failed"
@@ -52,174 +54,91 @@ run_build() {
     unset -f prebuild build postbuild
 }
 
-# * export all compilation related flags to environment
-#
-# * if given '--no-static' as an argument, will omit
-#   all static-compilation related CFLAGS and LDFLAGS
-#
-# params: [--no-static]
-getflags() {
-    # 1. users config flags
-    CFLAGS="$cflags"
-    LDFLAGS="$ldflags"
-
-    # 2. performance / general flags
-    CFLAGS="$CFLAGS -Wl,--gc-sections -pipe"
-    LDFLAGS="$LDFLAGS -fdata-sections -ffunction-sections"
-
-    # 3. security flags
-    CFLAGS="$CFLAGS -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS \
--fexceptions -fstack-protector-strong -fstack-clash-protection \
--fasynchronous-unwind-tables -fcf-protection \
--Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -Wl,-z,nodump"
-
-    # 4. static related flags
-    case "$1" in
-        --no-static)
-            LIBTOOL=/bin/slibtool
-            PKG_CONFIG=/bin/pkgconf
-            ;;
-        *)
-            CFLAGS="$CFLAGS -static --static -static-libgcc -static-libstdc++ \
--Wl,-Bstatic -fpic -Wl,-z,nodlopen"
-            LDFLAGS="$LDFLAGS -static --static"
-            AM_LDFLAGS="$AM_LDFLAGS -static --static"
-            LIBTOOL=/bin/slibtool-static
-            PKG_CONFIG=/bin/pkgconf-static
-    esac
-
-    LIBRARY_PATH=".:$root/lib:$root/libexec"
-    CPATH=".:$root/include"
-    CPPFLAGS="$CPPFLAGS $cppflags"
-    CXXFLAGS="$CXXFLAGS $cxxflags"
-    DESTDIR="$pkgs/$name"
-    PREFIX=/
-    prefix=/
-    BINDIR="$PREFIX"/bin
-    DOCDIR="$PREFIX"/sucks
-    cc="${cc:=$gcc}"
-    CC="${cc:=$cc}"
-    HOSTCC="$CC"
-    MAKEINFO=false
-    PKG_CONFIG_PATH="$root/lib/pkgconfig:$root/share/pkgconfig"
-    SHELL=/bin/sh
-
-    # fix tool vars if we're bootstrapping 
-    type slibtool >/dev/null 2>&1 || export LIBTOOL="$(which libtool)"
-    type pkgconf  >/dev/null 2>&1 || export PKG_CONFIG="$(which pkg-config)"
-
-    # commonly needed variables
-    : ${GREP:=grep} ${FGREP:=fgrep} ${EGREP:=egrep} ${SED:=sed} ${AWK:=awk} \
-      ${TAR:=tar} ${FIND:=find} ${YACC:=yacc}
-
-    export TARGET HOST BUILD CC cc HOSTCC SHELL LIBRARY_PATH CPATH \
-           PKG_CONFIG_PATH PKG_CONFIG CFLAGS LDFLAGS CPPFLAGS CXXFLAGS \
-           PREFIX prefix DOCDIR BINDIR MAKEINFO \
-           GREP FGREP EGREP SED AWK TAR FIND YACC
-}
-
 # convenience function, tries to find all *.patch
-# in the top-level $workdir/$name directory and apply them
+# in the top-level $WORK/$name directory and apply them
 bonsai_patch() {
     find . ! -name . -prune -name "*.patch" | while read -r patch ; do
-        msg "$(patch -u -f -l -p0 < "$patch")" || die "$patch failed"
+        patch -u -f -l -p0 <"$patch" || die "$patch failed"
     done
 }
-
-bonsai_autogen() { sh autogen.sh "$@" || die "autogen.sh failed for $name" ; }
 
 # if --path= param is provided, use ./"$path"/configure
 # instead of assumed "./configure" (ie ./"$PWD"/configure)
 # possible params: --path=""
 bonsai_configure() {
-    # set path to the configure script, if provided
     case "$1" in
-        --path=*) cfpath="${1#--path=}" ; shift ;;
-        *) cfpath="$PWD"
+        --path=*) cfpath="${1#--path=*}" ; shift ;;
+               *) cfpath="$PWD"
     esac
 
     # try to enable as many options as possible
     # if they are allowed in the configure script
-    cfflags="$workdir"/cfflags
-    cfhelp="$(sh "$cfpath"/configure --help | tee "$workdir"/cfhelp)"
-    :> "$cfflags"
+    cfhelp="$(sh "$cfpath"/configure --help | tee "$WORK"/$name/cfhelp)"
+    cfflags=
 
-    # params: flag_to_check flag_to_add
-    addflag() {
+    # save flags from pkgfile so they don't get overwritten by set
+    pkg_cfflags="$@"
+
+    YES() {
         case "$cfhelp" in
-            *"$1"*)
-                echo "$2" >> "$cfflags"
-                msg "adding flag: $2"
+            *" --enable-$1 "*|*" --disable-$1 "*)
+                cfflags="$cfflags --enable-$1 "
+                msg "adding flag: --enable-$1 "
+                ;;
+            *" --with-$1 "*|*" --without-$1 "*)
+                cfflags="$cfflags --with-$1 "
+                msg "adding flag: --with-$1 "
+        esac
+    }
+    NO() {
+        case "$cfhelp" in
+            *" --disable-$1 "*|*" --enable-$1 "*)
+                cfflags="$cfflags --disable-$1 "
+                msg "adding flag: --disable-$1 "
+                ;;
+            *" --without-$1 "*|*" --with-$1 "*)
+                cfflags="$cfflags --without-$1 "
+                msg "adding flag: --without-$1 "
+        esac
+    }
+    SET() {
+        case "$cfhelp" in
+            *" --$1="*)
+                cfflags="$cfflags --$1=$2 "
+                msg "adding flag: --$1=$2 "
+                ;;
+            *" --$1 "*)
+                cfflags="$cfflags --$1 "
+                msg "adding flag: --$1 "
         esac
     }
 
-    # -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
-    # Global configure flags. These are applied to all packages.
-    #
-    # set in bonsai.rc:
-    [ "${nls:=false}" = false ] && _nls=--disable-nls
-    [ "${quiet:=false}" = true ] && _quiet='--silent --quiet'
-    #
-    # flags that are the same as what we check for
-    for flag in --static --enable-static --enable-static-link --all-static \
-                --disable-shared --without-shared --disable-rpath \
-                --with-pic --enable-pic \
-                --disable-option-checking --disable-dependency-tracking \
-                --enable-fast-install --disable-largefile --disable-libtool-lock \
-                --disable-docs --disable-gtk-docs --disable-gtk-docs-html \
-                --disable-documentation --disable-devel-docs --disable-build-docs \
-                --without-asciidoc --without-tests --disable-tests \
-                --without-debug --disable-debug --disable-debugger \
-                --without-gettext --without-ada $_quiet $_nls ; do
-        addflag $flag $flag
+    while read -r line ; do
+        set -- $line
+        case $1 in
+            SET) SET $2 $3 ;;
+            YES) YES $2 ;;
+            NO)  NO  $2 ;;
+        esac
+    done <"$CONFIG"/autotools.cfg
+
+    # store flags used to a file for convenience
+    for flag in $cfflags $pkg_cfflags ; do
+        echo "$flag" >>"$WORK"/$name/cfflags
     done
-    #
-    # flags that are dynamic
-    addflag --enable-shared --disable-shared
-    addflag --with-shared --without-shared
-    addflag --disable-static --enable-static
-    addflag --with-gnu-ld --without-gnu-ld
-    addflag --with-debug --without-debug
-    addflag --enable-debug --disable-debug
-    addflag --enable-tests --disable-tests
-    addflag --with-tests --without-tests
-    addflag --with-doc= --with-doc=no
-    addflag --with-doxygen --without-doxygen
-    addflag --with-gettext --without-gettext
-    addflag --enable-documentation --disable-documentation
-    addflag --with-xmlto --without-xmlto
-    addflag --with-fop --without-fop
-    addflag --with-xsltproc --without-xsltproc
-    addflag --prefix= --prefix=/
-    addflag --sysconfdir= --sysconfdir=/etc
-    addflag --libdir= --libdir=/lib
-    addflag --libexecdir= --libexecdir=/lib
-    addflag --infodir= --infodir=/sucks
-    addflag --docdir= --docdir=/sucks
-    addflag --htmldir= --htmldir=/sucks
-    # -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 
-    # add a new line to denote separation between global flags
-    # and argument-supplied flags
-    echo >> "$cfflags"
-
-    # add all argument-supplied flags to the flag file
-    for flag in "$@" ; do echo "$flag" ; done >> "$cfflags"
-
-    sh "$cfpath"/configure $(shellcat "$cfflags") || 
+    sh "$cfpath"/configure $cfflags $pkg_cfflags || 
         die "configure failed for $name"
 }
 
 bonsai_make() {
-    # set in bonsai.rc:
-    [ "${quiet:=false}"   = true  ] && _quiet='-s'
-    [ "${verbose:=false}" = true  ] && _verbose='V=1'
-
-    make $_verbose $_quiet $makeflags -j${jobs:=1} CC="$CC" cc="$CC" \
-        LIBTOOL="$LIBTOOL" MAKE="make LIBTOOL='$LIBTOOL'" PKG_CONFIG="$PKG_CONFIG" \
-        DESTDIR="$DESTDIR" PREFIX="$PREFIX" prefix="$PREFIX" DOCDIR="$DOCDIR" \
-        BINDIR="$BINDIR" SBINDIR="$BINDIR" bindir="$BINDIR" sbindir="$BINDIR" \
-        "$@" || die "make $* failed for $name"
+    make -j${JOBS:-1} $([ "$VERBOSE" ] && echo V=1) \
+    CC="$CC" cc="$CC" CXX="$CXX" cxx="$CXX" \
+    LIBTOOL="$LIBTOOL" MAKE="make LIBTOOL='$LIBTOOL'" PKG_CONFIG="$PKG_CONFIG" \
+    DESTDIR="$DESTDIR" PREFIX="$PREFIX" prefix="$PREFIX" DOCDIR="$DOCDIR" \
+    BINDIR="$BINDIR" SBINDIR="$BINDIR" LIBDIR="$LIBDIR" LIBEXECDIR="$LIBEXECDIR" \
+    libdir="$LIBDIR" bindir="$BINDIR" sbindir="$BINDIR" libexecdir="$LIBEXECDIR" \
+    MAKEINFO=false MKDIR_P="$MKDIR_P" "$@" || die "make $* failed for $name"
 }
 
 # run if pkgfile doesn't define a custom build()
@@ -227,9 +146,40 @@ generic_build() {
     if [ -f configure ] ; then
         bonsai_configure || return 1
     elif [ -f autogen.sh ] ; then
-        bonsai_autogen || return 1
+        sh autogen.sh || return 1
         bonsai_configure || return 1
     fi
     bonsai_make || return 1
     bonsai_make install || return 1
+}
+
+getflags() {
+    # import user's flags and export them
+    isinst @cfg >/dev/null && . "$CONFIG"/build.cfg
+
+    case "$1" in
+        --no-static)
+            LIBTOOL=/bin/slibtool
+            PKG_CONFIG=/bin/pkgconf
+            ;;
+        *)
+            CFLAGS="$CFLAGS $STATIC_CFLAGS"
+            LDFLAGS="$LDFLAGS $STATIC_LDFLAGS"
+            LIBTOOL=/bin/slibtool-static
+            PKG_CONFIG=/bin/pkgconf-static
+    esac
+
+    # fix slibtool/pkgconf if we're bootstrapping
+    test -x /bin/slibtool >/dev/null 2>&1 || LIBTOOL=libtool
+    test -x /bin/pkgconf  >/dev/null 2>&1 || PKG_CONFIG=pkg-config
+
+    # system flags
+    export DESTDIR="$PKGS/$name" PREFIX=/ prefix=/ DOCDIR="$PREFIX"/sucks \
+    SHELL=/bin/sh HOSTCC="$CC" cc="$CC" GREP=grep FGREP=fgrep EGREP=egrep \
+    SED=sed FIND=find AWK=awk TAR=tar YACC=yacc MKDIR_P='install -d'
+
+    # user cfg flags
+    export CC CXX AR AS RANLIB STRIP LIBTOOL PKG_CONFIG JOBS \
+           CFLAGS LDFLAGS JOBS LIBRARY_PATH LD_LIBRARY_PATH CPATH \
+           PKG_CONFIG_PATH BINDIR LIBDIR SBINDIR LIBEXECDIR MANDIR 
 }
diff --git a/src/get b/src/get
--- a/src/get
+++ b/src/get
@@ -1,123 +1,60 @@
+# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
+# get                    http://github.com/bonsai-linux/bonsai
+# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 # vi:syntax=sh
 # shellcheck shell=sh
+# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 
-# downloads url and extracts to $workdir/$pkg
+# downloads url and extracts to $pkgworkdir
 # params: none
-# assumes: $version $source $pkgid $pkgfile $pkgworkdir in environment
+# assumes: $name $version $source $pkgid $pkgfile $pkgworkdir in environment
 get() {
-    name="$1"
-    dldir="$workdir/dl"
-    mkdir -p "$pkgworkdir" "$dldir" "$sources"
-
-    # get file extension
-    # if is a metapkg or using git, there will be no extension
-    case "$version" in
-        git|metapkg|none) ext="" ;;
-        *) ext="$(get_ext "$source")"
-    esac
+    mkdir -p "$SOURCES" "$pkgworkdir"
+    get_ext "$source"
 
     # do not try to dl / extract if metapkg or source=none
-    if [ "$version" != metapkg ] && [ "$source" != none ] ; then
-        # download tarball only if not in $sources
-        if [ ! -e "$sources/$pkgid$ext" ] ; then
-            dlcurl "$source" "$name" "$version" || 
-                die "get(): could not download $name"
-            verify_checksum "$dldir/$pkgid$ext"
-            [ "$DLONLY" ] || extract "$dldir/$pkgid$ext"
-        else
-            verify_checksum "$sources/$pkgid$ext"
-            [ "$DLONLY" ] || extract "$sources/$pkgid$ext"
+    [ ! -f "$SOURCES/$pkgid$ext" ] && \
+    [ "$source" ] && [ "$source" != none ] && \
+    dlcurl "$source" "$SOURCES" "$pkgid$ext"
+
+    if [ ! "$DL_ONLY" ] ; then
+        if ! ismetapkg $name ; then
+            [ "$sha512" ] && verify_checksum "$SOURCES/$pkgid$ext" "$sha512"
+            [ "$sha256" ] && verify_checksum "$SOURCES/$pkgid$ext" "$sha256"
+            extract "$SOURCES/$pkgid$ext" "$pkgworkdir"
         fi
+        # copy all port's files, except its pkgfile -- (ex: patches)
+        find "$(getportdir $name)" -type f ! -name pkgfile ! -name $name | \
+        while read -r file ; do
+            cp -f "$file" "$pkgworkdir"/
+        done
     fi
-
-    # copy all port's files, except its pkgfile -- (ex: patches)
-    [ "$DLONLY" ] ||
-    find "$ports/$name" -type f ! -name pkgfile ! -name $name | while read -r file ; do
-        cp -f "$file" "$pkgworkdir"/
-    done
 }
 
-# NOTE: Downloading via git comes highly unrecommended.
-#       This makes packages depend on git, which is
-#       a rather large dependency for otherwise small programs.
-#       Instead, download a tarball from a commit hash using this format:
-#       version=<SHA_HASH>
-#       source=http://github.com/<GITHUB_USER>/$name/archive/$version.tar.gz
-# dlgit() {
-    # todo - see issue #6
-# }
-
-# downloads given url to $sources
-# params: $source $name $version
+# params: $url $outdir $filename
 dlcurl() {
-    type curl >/dev/null 2>&1 || die "curl does not seem to be installed."
-
-    _dldir="$workdir"/dl
-    _source="$1"
-    _name="$2"
-    _version="$3"
-    _pkgid="$_name$delim$_version"
-    _ext="$(get_ext "$_source")"
-    mkdir -p "$_dldir"
-    msg "downloading $_source..."
-
-    # curl bugs out with certain delimiters, as a fix
+    msg "downloading $3..."
+    # curl bugs out with certain characters in filenames, as a fix
     # have curl output to a temporary file, then rename.
-    curl -q -L -C - -# --url "$_source" -o "$_dldir/curl-$_name-dl$_ext"
-    mv -f "$_dldir/curl-$_name-dl$_ext" "$_dldir/$_pkgid$_ext"
-
-    [ "${keep_tarballs:=true}" = true ] && 
-        cp -f "$_dldir/$_pkgid$_ext" "$sources"/
+    curl -q -L -C - -# --url "$1" -o "$2/$$.dlcurl" || die "failed to download $3"
+    mv -f -- "$2/$$.dlcurl" "$2/$3"
 }
 
-# returns the extension from given url
 # params: $source
 get_ext() {
-    set -- "$1" ".${1##*.}"
     case "$1" in
-        *.tar.*) echo ".tar$2" ;;
-        *) echo "$2"
+        *.tar.*) ext=".tar.${1##*.}" ;;
+              *) ext=".${1##*.}"
     esac
 }
 
-# verifies hash of $tarball against hash in the pkgfile
-# params: $tarball
-# assumes: one of the following: $sha{512,256,1} or $md5 in the environment
-verify_checksum() {
-    [ "$1" ] || die "verify_checksum(): no tarball provided"
-    msg_no_nl "comparing checksum for $(basename "$1" | sed "s|$delim.*||")... "
-
-    if   [ "$sha512" ] ; then set -- "$sha512" $(sha512sum "$1") "$1"
-    elif [ "$sha256" ] ; then set -- "$sha256" $(sha256sum "$1") "$1"
-    elif [ "$sha1"   ] ; then set -- "$sha1"   $(sha1sum "$1")   "$1"
-    elif [ "$md5"    ] ; then set -- "$md5"    $(md5sum "$1")    "$1"
-    else
-        # if unable to validate checksum, prompt user to confirm to continue
-        printf "\n"
-        warn "no checksum defined for $1"
-        confirm
-        case $? in
-            0) return ;;
-            *) die 'exiting'
-        esac
-    fi
-
-    # compare the hashes
-    if [ "$1" = "$2" ] ; then
-        printf "%s\n" "matched!"
-    else
-        printf "\n"
-        die "checksum mismatch for $3"
-    fi
-}
-
-# decompresses a given tarball to stdout
-# params: $tarball
+# decompress a given tarball to stdout
 decompress() {
+    [ -f "$1" ] || die "decompress: no such file $1"
     case "${1##*.}" in
         xz|txz) 
             if type xz-embedded >/dev/null 2>&1 ; then
-                xz-embedded < "$1"
+                xz-embedded <"$1"
             else
                 xz -qdc "$1"
             fi
@@ -125,29 +62,45 @@ decompress() {
         gz|tgz)  gunzip  -qdc  "$1" ;;
         bz2|tbz) bunzip2 -qdc  "$1" ;;
         zip)     unzip   -qp   "$1" ;;
-    esac || die "get(): failed to decompress $1"
+        *) die "decompress: unsupported filetype"
+    esac || die "decompress: failed to decompress $1"
 }
 
-# compares checksum for given tarball and extracts to $pkgworkdir
-# params: $tarball
-# assumes: $name, $ext, $dldir, $pkgworkdir
+# decompress and extract a given tarball "$1" to folder "$2"
 extract() {
-    msg "extracting $name..."
-    mkdir -p "$dldir" "$pkgworkdir"
+    [ -f "$1" ] || die "extract: no such file $1"
+    get_ext "$1"
+    mkdir -p -- "$2"
     case "$ext" in
-        .tar.*|.tgz)
-            { decompress "$1" | tar -C "$dldir" -xf - ; } || 
-                die "failed to decompress $1"
+        .tar.*|.tgz|.tbz|.txz)
+            { decompress "$1" | tar -C "$2" -xf - ; } || 
+                die "extract: failed to decompress $1"
+
+            dldir="$2/$(ls "$2")"
+
             # ensure files are in toplevel (ie $dir/name, not $dir/$name/$name)
-            mv -f "${dldir:?}"/*/* "${pkgworkdir:?}"/
+            mv -f -- "$dldir"/* "$2"/ 2>/dev/null
+
             # copy any hidden files
-            find "$dldir" -name ".*" ! -name '.' | while read -r file ; do
-                mv "$file" "${pkgworkdir:?}"/
-            done
+            find "$dldir" -name ".*" ! -name . -exec mv -f "{}" "$2"/ 2>/dev/null \;
+
             # try to remove possible empty dirs
-            rmdir "$dldir"/* "$dldir" 2>/dev/null ||:
+            rmdir "$dldir" 2>/dev/null ||:
             ;;
-        # if not a tarball, simply write to $pkgworkdir
-        *) decompress "$1" > "${pkgworkdir:?}/${1%%$ext}"
-    esac || die "get(): failed to extract $1"
+        *)  # if not a tarball, simply write it out
+            file="$(basename "$1")"
+            decompress "$1" >"$2/${file%%$ext}"
+    esac || die "extract: failed to extract $1"
+}
+
+verify_checksum() {
+    msg_no_nl "verifying checksums... "
+    case "${#2}" in
+        128) set -- $@ sha512sum ;;
+         64) set -- $@ sha256sum ;;
+          *) die "bad SHA sum provided"
+    esac
+    set -- "${2:-?}" $($3 "$1" 2>/dev/null)
+    [ "$1" = "$2" ] && echo "matched!" || 
+    { >&2 echo "CHECKSUM MISMATCH" ; exit 1 ; }
 }
diff --git a/src/link b/src/link
--- a/src/link
+++ b/src/link
@@ -1,138 +1,108 @@
+# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
+# link                   http://github.com/bonsai-linux/bonsai
+# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 # vi:syntax=sh
 # shellcheck shell=sh
+# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 
 # create symlinks for a port
 # params: $name [$pkgs]
-# assumes: all pkgfile variables in environment
-#
-# * If $pkgs is not provided, use the config's
+# * If $pkgs is not provided, use the config's $PKGS
 #
 # * If it is provided, symlink targets using this value.
 #   This is useful for bootstrapping, as after chrooting in
 #   if you had not done this all of your symlinks would be broken.
 linkpkg() {
-    [ "$1" ] || die "linkpkg(): invalid number of arguments"
-    name="$1" 
+    [ "$nolink" = true ] && return
 
+    name="$1" 
     case $# in
-        1) _pkgs="$pkgs" ;;
-        2) _pkgs="$2" ;;
+        1) pkgs="$PKGS" ;;
+        2) pkgs="$2" ;;
         *) die "linkpkg(): invalid number of arguments"
     esac
 
-    [ "$nolink" = true ] && return
-
-    if [ ! -d "$pkgs/$name" ] ; then
+    if [ ! -d "$PKGS/$name" ] ; then
         ismetapkg "$name" && return
-        die "linkpkg(): $name doesn't appear to be in $pkgs"
+        die "linkpkg(): $name doesn't appear to be in \$PKGS"
     fi
 
-    cd "$root" || die "linkpkg(): unable to cd to $root"
+    cd "$ROOT" || die "linkpkg(): unable to cd to $ROOT"
     msg "creating symlinks for $name..."
 
     for dir in bin sbin share include etc lib libexec ; do
-        if [ -d "$pkgs/$name/$dir" ] ; then
+        if [ -d "$PKGS/$name/$dir" ] ; then
             # recursively create pkg subdirectories in
-            # equivalent $root subdirectories
-            # example: $name/lib/pkgconfig -> $root/lib/pkgconfig
-            find "$pkgs/$name/$dir" ! -path "*$dir" \
-                    -type d 2> /dev/null | while read -r subdir ; do
-                mkdir -p "${subdir#$pkgs/$name/}"
+            # equivalent $ROOT subdirectories
+            # example: $name/lib/pkgconfig -> $ROOT/lib/pkgconfig
+            find "$PKGS/$name/$dir" ! -path "*$dir" \
+                    -type d 2>/dev/null | while read -r subdir ; do
+                mkdir -p -- "${subdir#$PKGS/$name/}"
             done
 
             # recursively link all files
-            # example: $name/include/asm/*.h -> $root/include/asm/*.h
-            find "$pkgs/$name/$dir" ! -path "*share/*man*" \
-                    -type f -o -type l 2> /dev/null | while read -r file ; do
-                file="${file#$pkgs/$name/}"
-                ln -sf "$_pkgs/$name/$file" "$file" 2>/dev/null
+            # example: $name/include/asm/*.h -> $ROOT/include/asm/*.h
+            find "$PKGS/$name/$dir" ! -path "*share/*man*" \
+                    -type f -o -type l 2>/dev/null | while read -r file ; do
+                file="${file#$PKGS/$name/}"
+                ln -sf "$pkgs/$name/$file" "$file" 2>/dev/null
             done
         fi &
     done
 
     for manX in man1 man2 man3 man4 man5 man6 man7 man8 ; do
-        if [ -d "$pkgs/$name/share/man/$manX" ] ; then
-            find "$pkgs/$name/share/man/$manX" \
-                    ! -path "*/$manX" 2> /dev/null | while read -r man ; do
-                ln -sf "$_pkgs/$name/share/man/$manX/${man##*/}" \
-                    "${man#$pkgs/$name/}" 2>/dev/null
+        if [ -d "$PKGS/$name/share/man/$manX" ] ; then
+            find "$PKGS/$name/share/man/$manX" \
+                    ! -path "*/$manX" 2>/dev/null | while read -r man ; do
+                ln -sf "$pkgs/$name/share/man/$manX/${man##*/}" \
+                    "${man#$PKGS/$name/}" 2>/dev/null
             done
         fi &
     done
     wait
 }
 
-# relinks every package installed
-# used to fix broken / inconsistent symlinks
-# 
-# also is used to bootstrap systems under a different $root
-# 
-# params: [--pkgs=]
-# 
-# * If param is not provided, simply relink all using the config's $pkgs
-# 
-# * If param is provided, relink the world using the given $pkgs location
-#   See comment heading of linkpkg() for details.
-#   Alternatively, if using the standard /src/pkgs location you
-#   can specify --chroot as an alias for --pkgs=/src/pkgs
+# * relinks every package installed, used to fix broken / inconsistent symlinks
+# * also used to bootstrap systems under a different $ROOT
+# params: [--chroot]
 relink_world() {
-    [ "$2" ] && die "relink_all(): invalid number of arguments"
-
-    # if no args, use the $pkgs variable from the bonsai.rc
-    if [ -z "$1" ] ; then
-        relink_pkgs="$pkgs"
-        msg 'relinking world...'
-    else
-        # helper for the default location
-        [ "$1" = --chroot ] && set -- '--pkgs=/src/pkgs'
-
-        # check if $1 contains '--pkgs='
-        if [ "${1#*--pkgs=}" != "$1" ] ; then
-            # note: sed here to remove the double '//' incase
-            #       user appended a slash onto their argument
-            relink_pkgs="$(echo ${1#--pkgs=} | sed 's|\/$|\/|')"
-        else
-            die 'bad argument given to --relink-world'
-        fi
-        msg "relinking world with \$pkgs=$relink_pkgs..."
-    fi
-
-    printf '\n'
+    # if no args, use the $PKGS variable from the bonsai.rc
+    case "$1" in
+        --chroot) relink_pkgs=/src/pkgs ;;
+               *) relink_pkgs="$PKGS"
+    esac
+    msg "relinking world with \$PKGS=$relink_pkgs..."
+    echo
 
     listpkgs | while read -r pkgid ; do
         pkg="$(pkgid2pkg "$pkgid")"
-        if ! grep '^nolink=true$' "$ports/$pkg/pkgfile" >/dev/null ; then
+        if ! grep '^nolink=true$' "$(getpkgfile $pkg)" >/dev/null ; then
             # if its a metapkg, only link if it has a pkgdir
-            if ismetapkg "$pkg" && [ ! -d "$pkgs/$pkg" ] ; then
-                continue
-            else
-                linkpkg "$pkg" "$relink_pkgs"
-            fi
+            ismetapkg "$pkg" && [ ! -d "$PKGS/$pkg" ] && continue
+            linkpkg "$pkg" "$relink_pkgs"
         fi
-        unset pkg
     done || die "relink_world(): linking failed"
 
-    printf '\n'
+    echo
     msg 'done!'
 }
 
 # checks if links are still sane, (pointing to $pkgs on the correct root)
 # * if chrooted, they should point to the /src/pkgs/$name/bin/$name
 # * if NOT chrooted, they should point to the $root/src/pkgs/$name/bin/$name
-# params: none
-check_links() {
-    [ "$USE_HOST_PATH" ] && return
+# check_links() {
+#     [ "$USE_HOST_PATH" ] && return
 
-    # Test symlinks for a few coreutils to ensure links are valid.
-    # This will fail should they not exist, but if you don't 
-    # have coreutils, then your system is borked anyway.
-    for prog in cp grep printf ; do
-        [ -e "$root"/bin/$prog ] || die 'no coreutils yet installed?'
-        test_link "$root"/bin/$prog || err_bad_links
-    done
-}
+#     # Test symlinks for a few coreutils to ensure links are valid.
+#     # This will fail should they not exist, but if you don't 
+#     # have coreutils, then your system is borked anyway.
+#     for prog in cp grep printf ; do
+#         [ -e "$root"/bin/$prog ] || die 'no coreutils yet installed?'
+#         test_link "$root"/bin/$prog || err_bad_links
+#     done
+# }
 
-err_bad_links() {
-        die "World appears to still be linked as a chroot.
-         Use --relink-world without arguments to relink externally."
-}
+# err_bad_links() {
+#         die "World appears to still be linked as a chroot.
+#          Use --relink-world without arguments to relink externally."
+# }
diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -1,93 +1,28 @@
+# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
+# main                   http://github.com/bonsai-linux/bonsai
+# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 # vi:syntax=sh
 # shellcheck shell=sh
+# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 
-# unset any env variables that could interfere
-unset cc c99 c89 CC \
-CFLAGS LDFLAGS CPPFLAGS CXXFLAGS PKG_CONFIG \
-LIBRARY_PATH CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH \
-OBJC_INCLUDE_PATH LD_LIBRARY_PATH LIBDIR EXTRALIBDIR \
-LIBS INCLUDE
+[ "$1" = --debug ] && { shift ; set -ex ; }
 
-initglobals() {
-    if [ "$USE_HOST_PATH" = true ] ; then
-        # If bootstrapping, relinking the world
-        # use the host's userland. When bootstraping, programs
-        # will take preference in the $PATH as they install.
-        export PATH=".:$root/bin:$PATH"
-    else
-        # otherwise if not bootstrapping, ONLY use the chroot's tools
-        export PATH=".:$root/bin"
-    fi
-
-    # can offer significant speedup
-    export LC_ALL=C LANG=C
-}
+export LC_ALL=C LANG=C
+if [ "$BOOTSTRAP" ] ; then
+    export PATH=".:$ROOT/bin:$PATH"
+    [ "$ROOT" ] || { >&2 echo "Error: \$ROOT is not defined" ; exit 1 ; }
+else
+    export ROOT=/ PATH=/bin
+    . /src/config/global.cfg
+fi
 
 main() {
-    # if no arguments, just print a pretty tree
-    [ "$1" ] || { print_logo ; exit ; }
-
-    # misc options before real commands
-    case "$1" in
-        --debug) shift ; set -ex ;;
-    esac
-
-    # special arguments
-    case "$1" in
-        --bootstrap)
-            export BOOTSTRAP=true USE_HOST_PATH=true
-            loadconfig
-            initglobals
-            addpkg @stage0 || exit 1
-            # download stage1 so it may be installed once chrooted in
-            msg 'downloading additional sources...'
-            DLONLY=true NO_PROMPT=true addpkg --quiet @stage1 || 
-                die 'WARNING: failed to download @stage1!'
-            msg 'System has been bootstrapped! You may now chroot in...
-  Remember to install @stage1 once inside.'
-            exit
-            ;;
-        *relink*world)
-            loadconfig
-            export USE_HOST_PATH=true
-            initglobals
-            ;;
-        unpack)
-            loadconfig
-            if isinst sbase >/dev/null ; then
-                initglobals
-            else
-                export USE_HOST_PATH=true
-                initglobals
-            fi
-            ;;
-        --hosts-path) # force usage of host's path
-            loadconfig
-            export USE_HOST_PATH=true
-            initglobals
-            shift
-            ;;
-        *skeleton|skel)
-            loadconfig --skeleton
-            create_skeleton_config
-            exit $?
-            ;;
-        *) loadconfig
-           initglobals
-    esac
-
-    # check if our package symlinks are valid -- if not, error out
-    case " $1 $2 " in
-        # if relinking the world we know our symlinks will be currently incorrect
-        *relink*world*) ;;
-        *) check_links 
-    esac
-    
     while [ "$1" ] ; do
         case "$1" in
             # ---- variable setting -------
-            *dlonly) export DLONLY=true ; shift ;;
-            -y) export NO_PROMPT=true ; shift ;;
+            *dlonly|-dl) export DL_ONLY=1 ; shift ;;
+            -y) export NO_PROMPT=1 ; shift ;;
+            -v|V=1) export VERBOSE=1 ; shift ;;
             # -----------------------------
             *relink*world) relink_world "$2" ; exit $? ;;
             list|-l)   listpkgs      ; exit $? ;;
@@ -100,9 +35,8 @@ main() {
             rdeps)     rdeps  "$2"   ; exit $? ;;
             add|-a) shift ; addpkg "$@" ; exit $? ;;
             del|-d) shift ; delpkg "$@" ; exit $? ;;
-            update|-u) shift ; export UPDATE=true ; addpkg "$@" ; exit $? ;;
+            update|-u) shift ; export UPDATE=1 ; addpkg "$@" ; exit $? ;;
             *help|-h) usage ; exit ;;
-            *verbose|V=1) shift ; export verbose=true ;;
             relink|-r)
                 shift
                 while [ "$1" ] ; do
@@ -113,7 +47,7 @@ main() {
             isinst)
                 shift
                 while [ "$1" ] ; do
-                    isinst "$1"
+                    isinst "$1" || exit 1
                     shift
                 done
                 ;;
@@ -127,19 +61,7 @@ main() {
                     exit 1
                 fi
                 ;;
-            *)
-                
-                if [ "$1" ] ; then
-                    # If none matched and there is an argument,
-                    # we must be adding a package
-                    # and omitting the 'add' (convenience).
-                    # recurse again, adding the 'add' argument
-                    set -- add "$@"
-                else
-                    # otherwise must have no arguments
-                    # just print a pretty tree
-                    bonsai
-                fi
+            *) [ "$1" ] && set -- add "$@"
         esac
     done
 }
