utils, chroot: fixup $sudo->$SUDO

diff --git a/src/chroot b/src/chroot
--- a/src/chroot
+++ b/src/chroot
@@ -3,7 +3,7 @@
 
 enter_chroot() {
     set +e
-    sudo=$(get_sudo)
+    get_sudo
     if already_chrooted > /dev/null ; then
         unmount_drives
         already_chrooted &&
@@ -23,7 +23,7 @@ enter_chroot() {
     mv -f "$bonsairc".tmp "$bonsairc"
 
     mount_drives
-    $sudo chroot "$root" "$chroot_shell" -l -i
+    $SUDO chroot "$root" "$chroot_shell" -l -i
     unchroot
     set -e
 }
@@ -52,24 +52,24 @@ get_chroot_shell() {
 }
 
 mount_drives() {
-    sudo=$(get_sudo)
-    $sudo mount -o bind -t devtmpfs /dev "$root"/dev || die 'Could not mount.'
-    $sudo mount -o bind -t devpts /dev/pts "$root"/dev/pts
-    $sudo mount -o bind -t proc /proc "$root"/proc
-    $sudo mount -o bind -t sysfs /sys "$root"/sys
+    get_sudo
+    $SUDO mount -o bind -t devtmpfs /dev "$root"/dev || die 'Could not mount.'
+    $SUDO mount -o bind -t devpts /dev/pts "$root"/dev/pts
+    $SUDO mount -o bind -t proc /proc "$root"/proc
+    $SUDO mount -o bind -t sysfs /sys "$root"/sys
 }
 
 unmount_drives() {
-    sudo=$(get_sudo)
+    get_sudo
     tryumount() {
         path="$1"
-        if ! $sudo umount "$path" 2> /dev/null ; then
+        if ! $SUDO umount "$path" 2> /dev/null ; then
             msg "umount ${path} failed... trying to umount -f"
             sleep 1
-            if ! $sudo umount -f "$path" 2> /dev/null ; then
+            if ! $SUDO umount -f "$path" 2> /dev/null ; then
                 msg "umount -f ${path} failed... trying to umount -l"
                 sleep 1
-                if ! $sudo umount -l "$path" 2> /dev/null ; then
+                if ! $SUDO umount -l "$path" 2> /dev/null ; then
                     warn "WARNING: could  not umount -l ${path}!"
                 fi
             fi
@@ -83,7 +83,7 @@ unmount_drives() {
 }
 
 unchroot() {
-    sudo=$(get_sudo)
+    get_sudo
     unmount_drives
     if already_chrooted ; then
         unmount_drives
@@ -95,7 +95,7 @@ unchroot() {
     sed "s|root=.*|$old_config_root|" "$bonsairc" > "$bonsairc".tmp
     mv -f "$bonsairc".tmp "$bonsairc"
 
-    $sudo chown -R "$USER" "${root:?}"
+    $SUDO chown -R "$USER" "${root:?}"
 
     msg 'exited chroot!'
 }
