(!!!) name change - we are now 'bonsai' linux, hooray!

diff --git a/src/config b/src/config
--- a/src/config
+++ b/src/config
@@ -1,13 +1,13 @@
 loadconfig() {
     if [ "$config" ] ; then
-        distrorc="$config"
+        bonsairc="$config"
     elif [ -f /src/"$PKG_MGR_NAME".rc ] ; then
-        distrorc="/src/$PKG_MGR_NAME.rc"
+        bonsairc="/src/$PKG_MGR_NAME.rc"
     else 
-        distrorc="${HOME}/.local/$PKG_MGR_NAME/src/$PKG_MGR_NAME.rc"
-        [ ! -f "$distrorc" ] && create_skeleton_config
+        bonsairc="${HOME}/.local/$PKG_MGR_NAME/src/$PKG_MGR_NAME.rc"
+        [ ! -f "$bonsairc" ] && create_skeleton_config
     fi
-    . "$distrorc" || die "loadconfig(): could not source config"
+    . "$bonsairc" || die "loadconfig(): could not source config"
 
     if [ "$_root" ] ; then
         root="$_root"
@@ -16,14 +16,14 @@ loadconfig() {
    
     # set default variables if not in config file
     # and make necessary directories
-    mkdir -p "${root:="${HOME}/.local/distro"}" \
-             "${distrohome:="$root/src"}" \
-             "${pkgs:="$distrohome/pkgs"}" \
-             "${ports:="$distrohome/ports"}" \
-             "${sources:="$distrohome/sources"}" \
-             "${work:="$distrohome/work"}"
+    mkdir -p "${root:="${HOME}/.local/bonsai"}" \
+             "${bonsaihome:="$root/src"}" \
+             "${pkgs:="$bonsaihome/pkgs"}" \
+             "${ports:="$bonsaihome/ports"}" \
+             "${sources:="$bonsaihome/sources"}" \
+             "${work:="$bonsaihome/work"}"
 
-    : "${distrodb:="$distrohome/distro.db"}"
+    : "${bonsaidb:="$bonsaihome/bonsai.db"}"
 
     [ "$_gcc" ] && gcc="$_gcc"
 
@@ -47,8 +47,8 @@ create_skeleton_config() {
         echo "copying default config to ~/.local/$PKG_MGR_NAME/$PKG_MGR_NAME.rc"
     fi
 cat > "$path/$PKG_MGR_NAME".rc << "EOF"
-# distro root
-root=${HOME}/.local/distro
+# bonsai root
+root=${HOME}/.local/bonsai
 
 # compiling
 jobs=$(grep -c 'cpu cores' /proc/cpuinfo)
