pkgs: add unpack() ; more cleanup
unpack/pack: cannot use custom delim in file names due to URL compatbility

touchups

diff --git a/src/get b/src/get
--- a/src/get
+++ b/src/get
@@ -54,9 +54,11 @@ get() {
         # download tarball only if not in $sources
         if [ ! -e "$sources/$pkgid$ext" ] ; then
             dlcurl "$source" || die "get(): could not download $name"
-            extract "$dldir/$pkgid$ext" "$md5"
+            verify_checksum "$dldir/$pkgid$ext"
+            extract "$dldir/$pkgid$ext"
         else
-            extract "$sources/$pkgid$ext" "$md5"
+            verify_checksum "$sources/$pkgid$ext"
+            extract "$sources/$pkgid$ext"
         fi
     fi
 
@@ -106,8 +108,9 @@ verify_checksum() {
 }
 
 # decompresses a given tarball to stdout
+# params: tarball
 decompress() {
-    case "${ext##*.}" in
+    case "${1##*.}" in
         xz|txz) 
             if type xz-embedded >/dev/null ; then
                 xz-embedded < "$1"
@@ -123,15 +126,13 @@ decompress() {
 
 # compares checksum for given tarball and extracts to $pkgworkdir
 # params: tarball
-# assumes: 1. $name, $ext, $dldir, $pkgworkdir
-#          2. one of the following: sha{512,256,1} or md5 in the environment
+# assumes: $name, $ext, $dldir, $pkgworkdir
 extract() {
-    ismetapkg "$name" || verify_checksum "$1"
     msg "extracting $name..."
     mkdir -p "$dldir" "$pkgworkdir"
     case "$ext" in
         .tar.*|.tgz)
-            decompress "$1" | tar -C "$dldir" -xf - || die "failed to decompress $1"
+            { decompress "$1" | tar -C "$dldir" -xf - ; } || die "failed to decompress $1"
             # ensure files are in toplevel (ie $dir/name, not $dir/$name/$name)
             mv -f "${dldir:?}"/*/* "${pkgworkdir:?}"/
             # copy any hidden files
diff --git a/src/pkgs b/src/pkgs
--- a/src/pkgs
+++ b/src/pkgs
@@ -2,31 +2,38 @@
 # shellcheck shell=sh
 
 # tar up a package for release / distribution, placing result in $PWD
+# Notes: We force delim to be '-' here, this is to ensure web
+#        compatbility. (Ex: cannot have '#' natively in URLs)
 # params: $name
 pack() {
     requires 'pack()' tar xz
     isinst "$1" >/dev/null || die "$1 is not installed"
     [ -d "$pkgs/$1" ] || die "$1 was not found in \$pkgs"
-    file="$(pkg2pkgid "$1")".tar.xz
+    file="$(pkg2pkgid "$1" | sed "s/$delim/-/")".tar.xz
     { tar -C "$pkgs" -cf - "$1" | xz -T 0 -z - > "$file" ; } || \
         die "failed to compress $1"
     msg "successfully packed $1 as ./$file"
     unset file
 }
 
-# untar a downloaded package and install it with addpkg()
-# params: pkg.tar.xz
+# untar a downloaded binary package and install it.
+# params: name-version.tar.xz
 unpack() {
     pkgid="${1%.tar.xz}"
-    name="${pkgid%$delim*}"
-    version="${pkgid#$name$delim}"
+    name="${pkgid%-*}"
+    version="${pkgid#$name-}"
 
-    export pkgid name version
+    # clear any work from possible existing build
+    rm -rf "${work:?}" 2>/dev/null ||:
 
-    echo "pkgid: $pkgid"
-    echo "name: $name"
-    echo "version: $version"
+    # check if is already installed
+    isinst "$name" >/dev/null && die "port $name is already installed"
 
+    # unpack
+    { decompress "$1" | tar -C "$pkgs" -xf - ; } || die "failed to decompress $1"
+
+    # link and install
+    installpkg "$name" || die "$name failed to install"
     unload_pkgfile
 }
 
